# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Wed Jun 22 20:35:21 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1077, 708)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/gitbuster_logo.xcf")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_11 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.mainTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName(_fromUtf8("mainTabWidget"))
        self.rebaseTab = QtGui.QWidget()
        self.rebaseTab.setObjectName(_fromUtf8("rebaseTab"))
        self.gridLayout_12 = QtGui.QGridLayout(self.rebaseTab)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.detailsGroupBox = QtGui.QGroupBox(self.rebaseTab)
        self.detailsGroupBox.setMinimumSize(QtCore.QSize(0, 300))
        self.detailsGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.detailsGroupBox.setObjectName(_fromUtf8("detailsGroupBox"))
        self.detailsLayout = QtGui.QGridLayout(self.detailsGroupBox)
        self.detailsLayout.setObjectName(_fromUtf8("detailsLayout"))
        self.hexshaLabel = QtGui.QLabel(self.detailsGroupBox)
        self.hexshaLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hexshaLabel.setObjectName(_fromUtf8("hexshaLabel"))
        self.detailsLayout.addWidget(self.hexshaLabel, 0, 0, 1, 1)
        self.hexshaHolderLabel = QtGui.QLabel(self.detailsGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(212, 8, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 8, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.hexshaHolderLabel.setPalette(palette)
        self.hexshaHolderLabel.setText(_fromUtf8(""))
        self.hexshaHolderLabel.setObjectName(_fromUtf8("hexshaHolderLabel"))
        self.detailsLayout.addWidget(self.hexshaHolderLabel, 0, 1, 1, 1)
        self.authorLabel = QtGui.QLabel(self.detailsGroupBox)
        self.authorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.authorLabel.setObjectName(_fromUtf8("authorLabel"))
        self.detailsLayout.addWidget(self.authorLabel, 1, 0, 1, 1)
        self.authoredDateLabel = QtGui.QLabel(self.detailsGroupBox)
        self.authoredDateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.authoredDateLabel.setObjectName(_fromUtf8("authoredDateLabel"))
        self.detailsLayout.addWidget(self.authoredDateLabel, 2, 0, 1, 1)
        self.committerLabel = QtGui.QLabel(self.detailsGroupBox)
        self.committerLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.committerLabel.setObjectName(_fromUtf8("committerLabel"))
        self.detailsLayout.addWidget(self.committerLabel, 3, 0, 1, 1)
        self.commitDateLabel = QtGui.QLabel(self.detailsGroupBox)
        self.commitDateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commitDateLabel.setObjectName(_fromUtf8("commitDateLabel"))
        self.detailsLayout.addWidget(self.commitDateLabel, 4, 0, 1, 1)
        self.authorHolderLabel = QtGui.QLabel(self.detailsGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 55, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 55, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.authorHolderLabel.setPalette(palette)
        self.authorHolderLabel.setText(_fromUtf8(""))
        self.authorHolderLabel.setObjectName(_fromUtf8("authorHolderLabel"))
        self.detailsLayout.addWidget(self.authorHolderLabel, 1, 1, 1, 1)
        self.authoredDateHolderLabel = QtGui.QLabel(self.detailsGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 55, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 55, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.authoredDateHolderLabel.setPalette(palette)
        self.authoredDateHolderLabel.setText(_fromUtf8(""))
        self.authoredDateHolderLabel.setObjectName(_fromUtf8("authoredDateHolderLabel"))
        self.detailsLayout.addWidget(self.authoredDateHolderLabel, 2, 1, 1, 1)
        self.committerHolderLabel = QtGui.QLabel(self.detailsGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(11, 142, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(11, 142, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.committerHolderLabel.setPalette(palette)
        self.committerHolderLabel.setText(_fromUtf8(""))
        self.committerHolderLabel.setObjectName(_fromUtf8("committerHolderLabel"))
        self.detailsLayout.addWidget(self.committerHolderLabel, 3, 1, 1, 1)
        self.commitDateHolderLabel = QtGui.QLabel(self.detailsGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(11, 142, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(11, 142, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.commitDateHolderLabel.setPalette(palette)
        self.commitDateHolderLabel.setText(_fromUtf8(""))
        self.commitDateHolderLabel.setObjectName(_fromUtf8("commitDateHolderLabel"))
        self.detailsLayout.addWidget(self.commitDateHolderLabel, 4, 1, 1, 1)
        self.messageLabel = QtGui.QLabel(self.detailsGroupBox)
        self.messageLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.messageLabel.setObjectName(_fromUtf8("messageLabel"))
        self.detailsLayout.addWidget(self.messageLabel, 5, 0, 1, 1)
        self.messageHolderTextEdit = QtGui.QTextEdit(self.detailsGroupBox)
        self.messageHolderTextEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.messageHolderTextEdit.setMaximumSize(QtCore.QSize(250, 150))
        self.messageHolderTextEdit.setReadOnly(True)
        self.messageHolderTextEdit.setObjectName(_fromUtf8("messageHolderTextEdit"))
        self.detailsLayout.addWidget(self.messageHolderTextEdit, 6, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.detailsLayout.addItem(spacerItem, 7, 0, 1, 1)
        self.conflictsButton = QtGui.QPushButton(self.detailsGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(204, 33, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 33, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.conflictsButton.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.conflictsButton.setFont(font)
        self.conflictsButton.setObjectName(_fromUtf8("conflictsButton"))
        self.detailsLayout.addWidget(self.conflictsButton, 8, 0, 1, 2)
        self.detailsLayout.setColumnStretch(0, 1)
        self.detailsLayout.setColumnStretch(1, 2)
        self.gridLayout_12.addWidget(self.detailsGroupBox, 2, 0, 2, 2)
        self.groupBox_2 = QtGui.QGroupBox(self.rebaseTab)
        self.groupBox_2.setMinimumSize(QtCore.QSize(280, 40))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.branchCheckboxLayout = QtGui.QGridLayout(self.groupBox_2)
        self.branchCheckboxLayout.setObjectName(_fromUtf8("branchCheckboxLayout"))
        self.gridLayout_12.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.viewLayout = QtGui.QGridLayout()
        self.viewLayout.setObjectName(_fromUtf8("viewLayout"))
        self.gridLayout_12.addLayout(self.viewLayout, 1, 3, 3, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem1, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(0, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem2, 3, 5, 1, 1)
        self.mainTabWidget.addTab(self.rebaseTab, _fromUtf8(""))
        self.filterTab = QtGui.QWidget()
        self.filterTab.setObjectName(_fromUtf8("filterTab"))
        self.gridLayout = QtGui.QGridLayout(self.filterTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkboxLayout = QtGui.QGridLayout()
        self.checkboxLayout.setObjectName(_fromUtf8("checkboxLayout"))
        self.gridLayout.addLayout(self.checkboxLayout, 0, 0, 1, 2)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.currentBranchLabel = QtGui.QLabel(self.filterTab)
        self.currentBranchLabel.setObjectName(_fromUtf8("currentBranchLabel"))
        self.gridLayout_5.addWidget(self.currentBranchLabel, 0, 0, 1, 1)
        self.currentBranchComboBox = QtGui.QComboBox(self.filterTab)
        self.currentBranchComboBox.setMinimumSize(QtCore.QSize(80, 0))
        self.currentBranchComboBox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.currentBranchComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.currentBranchComboBox.setObjectName(_fromUtf8("currentBranchComboBox"))
        self.gridLayout_5.addWidget(self.currentBranchComboBox, 0, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(527, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)
        self.tableView = QtGui.QTableView(self.filterTab)
        self.tableView.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableView, 2, 0, 1, 2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mergeCheckBox = QtGui.QCheckBox(self.filterTab)
        self.mergeCheckBox.setChecked(False)
        self.mergeCheckBox.setObjectName(_fromUtf8("mergeCheckBox"))
        self.gridLayout_2.addWidget(self.mergeCheckBox, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(37, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(self.filterTab)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.filtersTab = QtGui.QWidget()
        self.filtersTab.setObjectName(_fromUtf8("filtersTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.filtersTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.filtersLayout = QtGui.QGridLayout()
        self.filtersLayout.setObjectName(_fromUtf8("filtersLayout"))
        self.beforeDateFilterDateEdit = QtGui.QDateEdit(self.filtersTab)
        self.beforeDateFilterDateEdit.setObjectName(_fromUtf8("beforeDateFilterDateEdit"))
        self.filtersLayout.addWidget(self.beforeDateFilterDateEdit, 1, 1, 1, 1)
        self.afterWeekdayFilterComboBox = QtGui.QComboBox(self.filtersTab)
        self.afterWeekdayFilterComboBox.setObjectName(_fromUtf8("afterWeekdayFilterComboBox"))
        self.afterWeekdayFilterComboBox.addItem(_fromUtf8(""))
        self.afterWeekdayFilterComboBox.addItem(_fromUtf8(""))
        self.afterWeekdayFilterComboBox.addItem(_fromUtf8(""))
        self.afterWeekdayFilterComboBox.addItem(_fromUtf8(""))
        self.afterWeekdayFilterComboBox.addItem(_fromUtf8(""))
        self.afterWeekdayFilterComboBox.addItem(_fromUtf8(""))
        self.afterWeekdayFilterComboBox.addItem(_fromUtf8(""))
        self.filtersLayout.addWidget(self.afterWeekdayFilterComboBox, 2, 1, 1, 1)
        self.beforeWeekdayFilterComboBox = QtGui.QComboBox(self.filtersTab)
        self.beforeWeekdayFilterComboBox.setObjectName(_fromUtf8("beforeWeekdayFilterComboBox"))
        self.beforeWeekdayFilterComboBox.addItem(_fromUtf8(""))
        self.beforeWeekdayFilterComboBox.addItem(_fromUtf8(""))
        self.beforeWeekdayFilterComboBox.addItem(_fromUtf8(""))
        self.beforeWeekdayFilterComboBox.addItem(_fromUtf8(""))
        self.beforeWeekdayFilterComboBox.addItem(_fromUtf8(""))
        self.beforeWeekdayFilterComboBox.addItem(_fromUtf8(""))
        self.beforeWeekdayFilterComboBox.addItem(_fromUtf8(""))
        self.filtersLayout.addWidget(self.beforeWeekdayFilterComboBox, 3, 1, 1, 1)
        self.afterWeekdayFilterCheckBox = QtGui.QCheckBox(self.filtersTab)
        self.afterWeekdayFilterCheckBox.setObjectName(_fromUtf8("afterWeekdayFilterCheckBox"))
        self.filtersLayout.addWidget(self.afterWeekdayFilterCheckBox, 2, 0, 1, 1)
        self.beforeDateFilterCheckBox = QtGui.QCheckBox(self.filtersTab)
        self.beforeDateFilterCheckBox.setObjectName(_fromUtf8("beforeDateFilterCheckBox"))
        self.filtersLayout.addWidget(self.beforeDateFilterCheckBox, 1, 0, 1, 1)
        self.beforeWeekdayFilterCheckBox = QtGui.QCheckBox(self.filtersTab)
        self.beforeWeekdayFilterCheckBox.setObjectName(_fromUtf8("beforeWeekdayFilterCheckBox"))
        self.filtersLayout.addWidget(self.beforeWeekdayFilterCheckBox, 3, 0, 1, 1)
        self.messageFilterCheckBox = QtGui.QCheckBox(self.filtersTab)
        self.messageFilterCheckBox.setObjectName(_fromUtf8("messageFilterCheckBox"))
        self.filtersLayout.addWidget(self.messageFilterCheckBox, 3, 2, 1, 2)
        self.beforeHourFilterCheckBox = QtGui.QCheckBox(self.filtersTab)
        self.beforeHourFilterCheckBox.setObjectName(_fromUtf8("beforeHourFilterCheckBox"))
        self.filtersLayout.addWidget(self.beforeHourFilterCheckBox, 1, 2, 1, 2)
        self.messageFilterLineEdit = QtGui.QLineEdit(self.filtersTab)
        self.messageFilterLineEdit.setObjectName(_fromUtf8("messageFilterLineEdit"))
        self.filtersLayout.addWidget(self.messageFilterLineEdit, 3, 4, 1, 1)
        self.beforeHourFilterTimeEdit = QtGui.QTimeEdit(self.filtersTab)
        self.beforeHourFilterTimeEdit.setObjectName(_fromUtf8("beforeHourFilterTimeEdit"))
        self.filtersLayout.addWidget(self.beforeHourFilterTimeEdit, 1, 4, 1, 1)
        self.nameEmailFilterCheckBox = QtGui.QCheckBox(self.filtersTab)
        self.nameEmailFilterCheckBox.setObjectName(_fromUtf8("nameEmailFilterCheckBox"))
        self.filtersLayout.addWidget(self.nameEmailFilterCheckBox, 2, 2, 1, 2)
        self.afterHourFilterTimeEdit = QtGui.QTimeEdit(self.filtersTab)
        self.afterHourFilterTimeEdit.setObjectName(_fromUtf8("afterHourFilterTimeEdit"))
        self.filtersLayout.addWidget(self.afterHourFilterTimeEdit, 0, 4, 1, 1)
        self.nameEmailFilterLineEdit = QtGui.QLineEdit(self.filtersTab)
        self.nameEmailFilterLineEdit.setObjectName(_fromUtf8("nameEmailFilterLineEdit"))
        self.filtersLayout.addWidget(self.nameEmailFilterLineEdit, 2, 4, 1, 1)
        self.afterDateFilterDateEdit = QtGui.QDateEdit(self.filtersTab)
        self.afterDateFilterDateEdit.setObjectName(_fromUtf8("afterDateFilterDateEdit"))
        self.filtersLayout.addWidget(self.afterDateFilterDateEdit, 0, 1, 1, 1)
        self.afterDateFilterCheckBox = QtGui.QCheckBox(self.filtersTab)
        self.afterDateFilterCheckBox.setObjectName(_fromUtf8("afterDateFilterCheckBox"))
        self.filtersLayout.addWidget(self.afterDateFilterCheckBox, 0, 0, 1, 1)
        self.afterHourFilterCheckBox = QtGui.QCheckBox(self.filtersTab)
        self.afterHourFilterCheckBox.setObjectName(_fromUtf8("afterHourFilterCheckBox"))
        self.filtersLayout.addWidget(self.afterHourFilterCheckBox, 0, 2, 1, 2)
        self.localOnlyFilterCheckBox = QtGui.QCheckBox(self.filtersTab)
        self.localOnlyFilterCheckBox.setObjectName(_fromUtf8("localOnlyFilterCheckBox"))
        self.filtersLayout.addWidget(self.localOnlyFilterCheckBox, 4, 0, 1, 1)
        self.filtersLayout.setColumnStretch(0, 1)
        self.filtersLayout.setColumnStretch(1, 1)
        self.filtersLayout.setColumnStretch(2, 1)
        self.filtersLayout.setColumnStretch(4, 1)
        self.gridLayout_4.addLayout(self.filtersLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.filtersTab, _fromUtf8(""))
        self.reorderTab = QtGui.QWidget()
        self.reorderTab.setObjectName(_fromUtf8("reorderTab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.reorderTab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.reOrderLabel = QtGui.QLabel(self.reorderTab)
        self.reOrderLabel.setObjectName(_fromUtf8("reOrderLabel"))
        self.gridLayout_6.addWidget(self.reOrderLabel, 0, 0, 1, 2)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.betweenDatesLabel = QtGui.QLabel(self.reorderTab)
        self.betweenDatesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.betweenDatesLabel.setObjectName(_fromUtf8("betweenDatesLabel"))
        self.gridLayout_8.addWidget(self.betweenDatesLabel, 0, 0, 1, 1)
        self.reOrderMinDateEdit = QtGui.QDateEdit(self.reorderTab)
        self.reOrderMinDateEdit.setObjectName(_fromUtf8("reOrderMinDateEdit"))
        self.gridLayout_8.addWidget(self.reOrderMinDateEdit, 0, 1, 1, 1)
        self.andDatesLabel = QtGui.QLabel(self.reorderTab)
        self.andDatesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.andDatesLabel.setObjectName(_fromUtf8("andDatesLabel"))
        self.gridLayout_8.addWidget(self.andDatesLabel, 0, 2, 1, 1)
        self.reOrderMaxDateEdit = QtGui.QDateEdit(self.reorderTab)
        self.reOrderMaxDateEdit.setObjectName(_fromUtf8("reOrderMaxDateEdit"))
        self.gridLayout_8.addWidget(self.reOrderMaxDateEdit, 0, 3, 1, 1)
        self.gridLayout_8.setColumnStretch(0, 1)
        self.gridLayout_8.setColumnStretch(1, 3)
        self.gridLayout_8.setColumnStretch(2, 1)
        self.gridLayout_8.setColumnStretch(3, 3)
        self.gridLayout_6.addLayout(self.gridLayout_8, 3, 1, 1, 1)
        self.reOrderDatesLabel = QtGui.QLabel(self.reorderTab)
        self.reOrderDatesLabel.setObjectName(_fromUtf8("reOrderDatesLabel"))
        self.gridLayout_6.addWidget(self.reOrderDatesLabel, 3, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 3, 2, 3, 1)
        self.reOrderPushButton = QtGui.QPushButton(self.reorderTab)
        self.reOrderPushButton.setObjectName(_fromUtf8("reOrderPushButton"))
        self.gridLayout_6.addWidget(self.reOrderPushButton, 6, 3, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.betweenHoursLabel = QtGui.QLabel(self.reorderTab)
        self.betweenHoursLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.betweenHoursLabel.setObjectName(_fromUtf8("betweenHoursLabel"))
        self.gridLayout_9.addWidget(self.betweenHoursLabel, 0, 0, 1, 1)
        self.reOrderMinTimeEdit = QtGui.QTimeEdit(self.reorderTab)
        self.reOrderMinTimeEdit.setObjectName(_fromUtf8("reOrderMinTimeEdit"))
        self.gridLayout_9.addWidget(self.reOrderMinTimeEdit, 0, 1, 1, 1)
        self.andHoursLabel = QtGui.QLabel(self.reorderTab)
        self.andHoursLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.andHoursLabel.setObjectName(_fromUtf8("andHoursLabel"))
        self.gridLayout_9.addWidget(self.andHoursLabel, 0, 2, 1, 1)
        self.reOrderMaxTimeEdit = QtGui.QTimeEdit(self.reorderTab)
        self.reOrderMaxTimeEdit.setTime(QtCore.QTime(23, 59, 0))
        self.reOrderMaxTimeEdit.setObjectName(_fromUtf8("reOrderMaxTimeEdit"))
        self.gridLayout_9.addWidget(self.reOrderMaxTimeEdit, 0, 3, 1, 1)
        self.gridLayout_9.setColumnStretch(0, 1)
        self.gridLayout_9.setColumnStretch(1, 3)
        self.gridLayout_9.setColumnStretch(2, 1)
        self.gridLayout_9.setColumnStretch(3, 3)
        self.gridLayout_6.addLayout(self.gridLayout_9, 4, 1, 2, 1)
        self.reOrderHoursLabel = QtGui.QLabel(self.reorderTab)
        self.reOrderHoursLabel.setObjectName(_fromUtf8("reOrderHoursLabel"))
        self.gridLayout_6.addWidget(self.reOrderHoursLabel, 4, 0, 2, 1)
        self.reOrderWeekdaysLabel = QtGui.QLabel(self.reorderTab)
        self.reOrderWeekdaysLabel.setObjectName(_fromUtf8("reOrderWeekdaysLabel"))
        self.gridLayout_6.addWidget(self.reOrderWeekdaysLabel, 2, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.reOrderWeekdayMondayCheckBox = QtGui.QCheckBox(self.reorderTab)
        self.reOrderWeekdayMondayCheckBox.setObjectName(_fromUtf8("reOrderWeekdayMondayCheckBox"))
        self.gridLayout_7.addWidget(self.reOrderWeekdayMondayCheckBox, 0, 0, 1, 1)
        self.reOrderWeekdayTuesdayCheckBox = QtGui.QCheckBox(self.reorderTab)
        self.reOrderWeekdayTuesdayCheckBox.setObjectName(_fromUtf8("reOrderWeekdayTuesdayCheckBox"))
        self.gridLayout_7.addWidget(self.reOrderWeekdayTuesdayCheckBox, 0, 1, 1, 1)
        self.reOrderWeekdayWednesdayCheckBox = QtGui.QCheckBox(self.reorderTab)
        self.reOrderWeekdayWednesdayCheckBox.setObjectName(_fromUtf8("reOrderWeekdayWednesdayCheckBox"))
        self.gridLayout_7.addWidget(self.reOrderWeekdayWednesdayCheckBox, 0, 2, 1, 1)
        self.reOrderWeekdayThursdayCheckBox = QtGui.QCheckBox(self.reorderTab)
        self.reOrderWeekdayThursdayCheckBox.setObjectName(_fromUtf8("reOrderWeekdayThursdayCheckBox"))
        self.gridLayout_7.addWidget(self.reOrderWeekdayThursdayCheckBox, 0, 3, 1, 1)
        self.reOrderWeekdayFridayCheckBox = QtGui.QCheckBox(self.reorderTab)
        self.reOrderWeekdayFridayCheckBox.setObjectName(_fromUtf8("reOrderWeekdayFridayCheckBox"))
        self.gridLayout_7.addWidget(self.reOrderWeekdayFridayCheckBox, 0, 4, 1, 1)
        self.reOrderWeekdaySaturdayCheckBox = QtGui.QCheckBox(self.reorderTab)
        self.reOrderWeekdaySaturdayCheckBox.setObjectName(_fromUtf8("reOrderWeekdaySaturdayCheckBox"))
        self.gridLayout_7.addWidget(self.reOrderWeekdaySaturdayCheckBox, 0, 5, 1, 1)
        self.reOrderWeekdaySundayCheckBox = QtGui.QCheckBox(self.reorderTab)
        self.reOrderWeekdaySundayCheckBox.setObjectName(_fromUtf8("reOrderWeekdaySundayCheckBox"))
        self.gridLayout_7.addWidget(self.reOrderWeekdaySundayCheckBox, 0, 6, 1, 1)
        self.label_5 = QtGui.QLabel(self.reorderTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_7.addWidget(self.label_5, 0, 7, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 2, 1, 1, 2)
        self.line = QtGui.QFrame(self.reorderTab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_6.addWidget(self.line, 1, 0, 1, 4)
        self.reOrderErrorsLabel = QtGui.QLabel(self.reorderTab)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(196, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.reOrderErrorsLabel.setPalette(palette)
        self.reOrderErrorsLabel.setText(_fromUtf8(""))
        self.reOrderErrorsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.reOrderErrorsLabel.setObjectName(_fromUtf8("reOrderErrorsLabel"))
        self.gridLayout_6.addWidget(self.reOrderErrorsLabel, 6, 0, 1, 3)
        self.gridLayout_10.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.reorderTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 4, 0, 1, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.mainTabWidget.addTab(self.filterTab, _fromUtf8(""))
        self.gridLayout_11.addWidget(self.mainTabWidget, 0, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.applyButton = QtGui.QPushButton(self.centralwidget)
        self.applyButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.gridLayout_3.addWidget(self.applyButton, 0, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(43, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 1, 1, 1)
        self.refreshButton = QtGui.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName(_fromUtf8("refreshButton"))
        self.gridLayout_3.addWidget(self.refreshButton, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1077, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionChange_repository = QtGui.QAction(MainWindow)
        self.actionChange_repository.setObjectName(_fromUtf8("actionChange_repository"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/system-log-out.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon1)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionUndo = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/mightyman_UndoRed.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon2)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/mightyman_RedoGreen.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon3)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionApply = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/jean_victor_balin_check.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionApply.setIcon(icon4)
        self.actionApply.setObjectName(_fromUtf8("actionApply"))
        self.actionHide_modifications = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/Hide.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHide_modifications.setIcon(icon5)
        self.actionHide_modifications.setObjectName(_fromUtf8("actionHide_modifications"))
        self.actionShow_modifications = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/Show.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_modifications.setIcon(icon6)
        self.actionShow_modifications.setObjectName(_fromUtf8("actionShow_modifications"))
        self.actionNew_branch = QtGui.QAction(MainWindow)
        self.actionNew_branch.setObjectName(_fromUtf8("actionNew_branch"))
        self.actionAbout_Gitbuster = QtGui.QAction(MainWindow)
        self.actionAbout_Gitbuster.setObjectName(_fromUtf8("actionAbout_Gitbuster"))
        self.menuFile.addAction(self.actionChange_repository)
        self.menuFile.addAction(self.actionNew_branch)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionApply)
        self.menuEdit.addAction(self.actionHide_modifications)
        self.menuEdit.addAction(self.actionShow_modifications)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuAbout.addAction(self.actionAbout_Gitbuster)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionApply)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHide_modifications)
        self.toolBar.addAction(self.actionShow_modifications)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.reOrderMinDateEdit, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), self.reOrderMaxDateEdit.setDate)
        QtCore.QObject.connect(self.reOrderPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.reOrderErrorsLabel.clear)
        QtCore.QObject.connect(self.reOrderMinDateEdit, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), self.reOrderErrorsLabel.clear)
        QtCore.QObject.connect(self.reOrderMaxDateEdit, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), self.reOrderErrorsLabel.clear)
        QtCore.QObject.connect(self.reOrderMaxTimeEdit, QtCore.SIGNAL(_fromUtf8("timeChanged(QTime)")), self.reOrderErrorsLabel.clear)
        QtCore.QObject.connect(self.reOrderMinTimeEdit, QtCore.SIGNAL(_fromUtf8("timeChanged(QTime)")), self.reOrderErrorsLabel.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.currentBranchComboBox, self.tableView)
        MainWindow.setTabOrder(self.tableView, self.mergeCheckBox)
        MainWindow.setTabOrder(self.mergeCheckBox, self.afterDateFilterCheckBox)
        MainWindow.setTabOrder(self.afterDateFilterCheckBox, self.afterDateFilterDateEdit)
        MainWindow.setTabOrder(self.afterDateFilterDateEdit, self.afterHourFilterCheckBox)
        MainWindow.setTabOrder(self.afterHourFilterCheckBox, self.afterHourFilterTimeEdit)
        MainWindow.setTabOrder(self.afterHourFilterTimeEdit, self.beforeDateFilterCheckBox)
        MainWindow.setTabOrder(self.beforeDateFilterCheckBox, self.beforeDateFilterDateEdit)
        MainWindow.setTabOrder(self.beforeDateFilterDateEdit, self.beforeHourFilterCheckBox)
        MainWindow.setTabOrder(self.beforeHourFilterCheckBox, self.beforeHourFilterTimeEdit)
        MainWindow.setTabOrder(self.beforeHourFilterTimeEdit, self.afterWeekdayFilterCheckBox)
        MainWindow.setTabOrder(self.afterWeekdayFilterCheckBox, self.afterWeekdayFilterComboBox)
        MainWindow.setTabOrder(self.afterWeekdayFilterComboBox, self.nameEmailFilterCheckBox)
        MainWindow.setTabOrder(self.nameEmailFilterCheckBox, self.nameEmailFilterLineEdit)
        MainWindow.setTabOrder(self.nameEmailFilterLineEdit, self.beforeWeekdayFilterCheckBox)
        MainWindow.setTabOrder(self.beforeWeekdayFilterCheckBox, self.beforeWeekdayFilterComboBox)
        MainWindow.setTabOrder(self.beforeWeekdayFilterComboBox, self.messageFilterCheckBox)
        MainWindow.setTabOrder(self.messageFilterCheckBox, self.messageFilterLineEdit)
        MainWindow.setTabOrder(self.messageFilterLineEdit, self.localOnlyFilterCheckBox)
        MainWindow.setTabOrder(self.localOnlyFilterCheckBox, self.reOrderWeekdayMondayCheckBox)
        MainWindow.setTabOrder(self.reOrderWeekdayMondayCheckBox, self.reOrderWeekdayTuesdayCheckBox)
        MainWindow.setTabOrder(self.reOrderWeekdayTuesdayCheckBox, self.reOrderWeekdayWednesdayCheckBox)
        MainWindow.setTabOrder(self.reOrderWeekdayWednesdayCheckBox, self.reOrderWeekdayThursdayCheckBox)
        MainWindow.setTabOrder(self.reOrderWeekdayThursdayCheckBox, self.reOrderWeekdayFridayCheckBox)
        MainWindow.setTabOrder(self.reOrderWeekdayFridayCheckBox, self.reOrderWeekdaySaturdayCheckBox)
        MainWindow.setTabOrder(self.reOrderWeekdaySaturdayCheckBox, self.reOrderWeekdaySundayCheckBox)
        MainWindow.setTabOrder(self.reOrderWeekdaySundayCheckBox, self.reOrderMinDateEdit)
        MainWindow.setTabOrder(self.reOrderMinDateEdit, self.reOrderMaxDateEdit)
        MainWindow.setTabOrder(self.reOrderMaxDateEdit, self.reOrderMinTimeEdit)
        MainWindow.setTabOrder(self.reOrderMinTimeEdit, self.reOrderMaxTimeEdit)
        MainWindow.setTabOrder(self.reOrderMaxTimeEdit, self.reOrderPushButton)
        MainWindow.setTabOrder(self.reOrderPushButton, self.applyButton)
        MainWindow.setTabOrder(self.applyButton, self.tabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "gitbuster", None, QtGui.QApplication.UnicodeUTF8))
        self.detailsGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.hexshaLabel.setText(QtGui.QApplication.translate("MainWindow", "Hexsha:", None, QtGui.QApplication.UnicodeUTF8))
        self.authorLabel.setText(QtGui.QApplication.translate("MainWindow", "Author:", None, QtGui.QApplication.UnicodeUTF8))
        self.authoredDateLabel.setText(QtGui.QApplication.translate("MainWindow", "Authored Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.committerLabel.setText(QtGui.QApplication.translate("MainWindow", "Commiter:", None, QtGui.QApplication.UnicodeUTF8))
        self.commitDateLabel.setText(QtGui.QApplication.translate("MainWindow", "Commit Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.messageLabel.setText(QtGui.QApplication.translate("MainWindow", "Message:", None, QtGui.QApplication.UnicodeUTF8))
        self.conflictsButton.setText(QtGui.QApplication.translate("MainWindow", "See conflicts", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Displayed Branches", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.rebaseTab), QtGui.QApplication.translate("MainWindow", "Rebase", None, QtGui.QApplication.UnicodeUTF8))
        self.currentBranchLabel.setText(QtGui.QApplication.translate("MainWindow", "Current branch :", None, QtGui.QApplication.UnicodeUTF8))
        self.mergeCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Update committed date/committer when authored date/author is changed", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeDateFilterDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Monday", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Tuedsay", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Wednesday", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Thursday", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Friday", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Saturday", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "Sunday", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Monday", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Tuedsay", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Wednesday", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Thursday", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Friday", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Saturday", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "Sunday", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "After weekday", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeDateFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Before date (dd/mm/yyyy)", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Before weekday", None, QtGui.QApplication.UnicodeUTF8))
        self.messageFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Match commit message", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeHourFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Before hour", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeHourFilterTimeEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.nameEmailFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Match name/email", None, QtGui.QApplication.UnicodeUTF8))
        self.afterHourFilterTimeEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.afterDateFilterDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.afterDateFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "After date (dd/mm/yyyy)", None, QtGui.QApplication.UnicodeUTF8))
        self.afterHourFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "After hour", None, QtGui.QApplication.UnicodeUTF8))
        self.localOnlyFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Local commits only", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.filtersTab), QtGui.QApplication.translate("MainWindow", "Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderLabel.setText(QtGui.QApplication.translate("MainWindow", "Re-order the displayed commits ", None, QtGui.QApplication.UnicodeUTF8))
        self.betweenDatesLabel.setText(QtGui.QApplication.translate("MainWindow", "between:", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderMinDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.andDatesLabel.setText(QtGui.QApplication.translate("MainWindow", "and:", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderMaxDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderDatesLabel.setText(QtGui.QApplication.translate("MainWindow", "Dates:", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderPushButton.setText(QtGui.QApplication.translate("MainWindow", "Re-order", None, QtGui.QApplication.UnicodeUTF8))
        self.betweenHoursLabel.setText(QtGui.QApplication.translate("MainWindow", "between:", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderMinTimeEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.andHoursLabel.setText(QtGui.QApplication.translate("MainWindow", "and:", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderMaxTimeEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderHoursLabel.setText(QtGui.QApplication.translate("MainWindow", "Hours:", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdaysLabel.setText(QtGui.QApplication.translate("MainWindow", "Weekdays :", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdayMondayCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Monday", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdayTuesdayCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Tuesday", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdayWednesdayCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Wednesday", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdayThursdayCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Thursday", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdayFridayCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Friday", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdaySaturdayCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Saturday", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdaySundayCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Sunday", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "(can be left blank)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reorderTab), QtGui.QApplication.translate("MainWindow", "Auto re-order", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.filterTab), QtGui.QApplication.translate("MainWindow", "Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("MainWindow", "&Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+A", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshButton.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_repository.setText(QtGui.QApplication.translate("MainWindow", "Change &repository", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("MainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionApply.setText(QtGui.QApplication.translate("MainWindow", "&Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.actionApply.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHide_modifications.setText(QtGui.QApplication.translate("MainWindow", "&Hide modifications", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_modifications.setText(QtGui.QApplication.translate("MainWindow", "Show modifications", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_branch.setText(QtGui.QApplication.translate("MainWindow", "New remote branch", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Gitbuster.setText(QtGui.QApplication.translate("MainWindow", "About Gitbuster", None, QtGui.QApplication.UnicodeUTF8))

import gitbuster_rc
