from distutils.core import setup

setup(name="nanolp",
    version="1.0g",
    description="Literate Programming Tool",
    long_description = open('README.txt').read(),
    author="Pavel Y",
    author_email="aquagnu@gmail.com",
    url='http://code.google.com/p/nano-lp/',
    download_url='http://nano-lp.googlecode.com/files/nanolp-1.0g.zip',
    packages = ["nanolp"],
    scripts=['bin/nlp.py', 'bin/lprc'],
    license='GNU GPLv2',
    keywords=['Literate Programming', 'Documentation'],
    classifiers = [
            'Development Status :: 3 - Alpha',
            'Environment :: Console',
            'Environment :: Other Environment',
            'Intended Audience :: Developers',
            'Intended Audience :: Science/Research',
            'License :: OSI Approved :: GNU General Public License v2 (GPLv2)',
            'Operating System :: OS Independent',
            'Programming Language :: Python',
            'Topic :: Documentation',
            'Topic :: Scientific/Engineering',
            'Topic :: Software Development :: Documentation',
            'Topic :: Text Processing :: Markup',
            'Topic :: Utilities',
        ],
)
