__version__ = "0.1.12"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'a5cf4f8d09114f85f55e68e1f5df771d470bcf65'
__git_head_subject__ = 'empty commit after version v0.1.11'
__git_head_message__ = ''
__git_dirty_diff__ = ''