__version__ = "0.3.9"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'a769cb3477b469b4093f8a44545c798e39ce75cb'
__git_head_subject__ = 'Finished release v0.3.9.'
__git_head_message__ = '* release/v0.3.9:\n  HOSTDEV-595 trivial\n  empty commit after version v0.3.8'
__git_dirty_diff__ = ''