__version__ = "0.5.4"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "wiggin15@yahoo.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'ab9145fc45c1b0a067c7bfaf964ca3a965760df6'
__git_head_subject__ = 'Finished release v0.5.4.'
__git_head_message__ = ''
__git_dirty_diff__ = ''