__version__ = "0.1.7"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "wiggin15@yahoo.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '03f331c6d11b8836c5616ea5a6332a7923bcff15'
__git_head_subject__ = 'empty commit after version v0.1.6'
__git_head_message__ = ''
__git_dirty_diff__ = ''