__version__ = "0.1"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '8fcd3d9a11d827291a27849ad25fba01aac3da82'
__git_head_subject__ = 'Finished release v0.1.'
__git_head_message__ = '# By Guy Rozendorn (2) and Arnon Yaari (1)\n* release/v0.1:\n  TRIVIAL skeleton update\n  TRIVIAL updated README.md\n  empty commit after version v0.0.1'
__git_dirty_diff__ = ''