__version__ = "0.3.3"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'a511e47b27914ca946a2c92a44f71c72bb7be74f'
__git_head_subject__ = 'empty commit after version v0.3.2'
__git_head_message__ = ''
__git_dirty_diff__ = ''