# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fccoelho/Documents/Projects_software/hidx/GUI/viz/motionchart.ui'
#
# Created: Sun Oct  7 18:38:40 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MotionChart(object):
    def setupUi(self, MotionChart):
        MotionChart.setObjectName(_fromUtf8("MotionChart"))
        MotionChart.resize(733, 592)
        self.gridLayout_2 = QtGui.QGridLayout(MotionChart)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.yVarCombo = QtGui.QComboBox(MotionChart)
        self.yVarCombo.setMinimumSize(QtCore.QSize(0, 28))
        self.yVarCombo.setMaximumSize(QtCore.QSize(16777215, 28))
        self.yVarCombo.setObjectName(_fromUtf8("yVarCombo"))
        self.horizontalLayout_2.addWidget(self.yVarCombo)
        self.yLog = QtGui.QCheckBox(MotionChart)
        self.yLog.setObjectName(_fromUtf8("yLog"))
        self.horizontalLayout_2.addWidget(self.yLog)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.plotTabWidget = QtGui.QTabWidget(MotionChart)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotTabWidget.sizePolicy().hasHeightForWidth())
        self.plotTabWidget.setSizePolicy(sizePolicy)
        self.plotTabWidget.setMinimumSize(QtCore.QSize(580, 400))
        self.plotTabWidget.setObjectName(_fromUtf8("plotTabWidget"))
        self.scatter = QtGui.QWidget()
        self.scatter.setObjectName(_fromUtf8("scatter"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scatter)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scatterLayout = QtGui.QVBoxLayout()
        self.scatterLayout.setObjectName(_fromUtf8("scatterLayout"))
        self.verticalLayout.addLayout(self.scatterLayout)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/motion/office-chart-scatter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.plotTabWidget.addTab(self.scatter, icon, _fromUtf8(""))
        self.histogram = QtGui.QWidget()
        self.histogram.setObjectName(_fromUtf8("histogram"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.histogram)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.histLayout = QtGui.QVBoxLayout()
        self.histLayout.setObjectName(_fromUtf8("histLayout"))
        self.verticalLayout_2.addLayout(self.histLayout)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/motion/office-chart-bar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.plotTabWidget.addTab(self.histogram, icon1, _fromUtf8(""))
        self.lines = QtGui.QWidget()
        self.lines.setObjectName(_fromUtf8("lines"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.lines)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lineLayout = QtGui.QVBoxLayout()
        self.lineLayout.setObjectName(_fromUtf8("lineLayout"))
        self.verticalLayout_4.addLayout(self.lineLayout)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/motion/office-chart-line.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.plotTabWidget.addTab(self.lines, icon2, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.plotTabWidget, 1, 0, 6, 1)
        self.label_2 = QtGui.QLabel(MotionChart)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.xLog = QtGui.QCheckBox(MotionChart)
        self.xLog.setObjectName(_fromUtf8("xLog"))
        self.horizontalLayout_3.addWidget(self.xLog)
        self.xVarCombo = QtGui.QComboBox(MotionChart)
        self.xVarCombo.setMinimumSize(QtCore.QSize(0, 28))
        self.xVarCombo.setMaximumSize(QtCore.QSize(16777215, 28))
        self.xVarCombo.setObjectName(_fromUtf8("xVarCombo"))
        self.horizontalLayout_3.addWidget(self.xVarCombo)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.timeLabel = QtGui.QLabel(MotionChart)
        self.timeLabel.setMaximumSize(QtCore.QSize(16777215, 29))
        self.timeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeLabel.setMargin(1)
        self.timeLabel.setIndent(0)
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self.gridLayout.addWidget(self.timeLabel, 0, 3, 1, 1)
        self.playButton = QtGui.QToolButton(MotionChart)
        self.playButton.setMaximumSize(QtCore.QSize(26, 26))
        self.playButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/motion/media-playback-start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/motion/media-playback-pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.playButton.setIcon(icon3)
        self.playButton.setCheckable(True)
        self.playButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.gridLayout.addWidget(self.playButton, 1, 0, 1, 1)
        self.playSpeed = QtGui.QSlider(MotionChart)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playSpeed.sizePolicy().hasHeightForWidth())
        self.playSpeed.setSizePolicy(sizePolicy)
        self.playSpeed.setMinimumSize(QtCore.QSize(18, 29))
        self.playSpeed.setMaximumSize(QtCore.QSize(23, 29))
        self.playSpeed.setMinimum(1)
        self.playSpeed.setMaximum(5)
        self.playSpeed.setPageStep(1)
        self.playSpeed.setOrientation(QtCore.Qt.Vertical)
        self.playSpeed.setObjectName(_fromUtf8("playSpeed"))
        self.gridLayout.addWidget(self.playSpeed, 1, 1, 1, 1)
        self.timeSlider = QtGui.QSlider(MotionChart)
        self.timeSlider.setMaximumSize(QtCore.QSize(16777215, 28))
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.timeSlider.setObjectName(_fromUtf8("timeSlider"))
        self.gridLayout.addWidget(self.timeSlider, 1, 2, 1, 2)
        self.timeCombo = QtGui.QComboBox(MotionChart)
        self.timeCombo.setObjectName(_fromUtf8("timeCombo"))
        self.gridLayout.addWidget(self.timeCombo, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 8, 0, 1, 1)
        self.colorCombo = QtGui.QComboBox(MotionChart)
        self.colorCombo.setObjectName(_fromUtf8("colorCombo"))
        self.gridLayout_2.addWidget(self.colorCombo, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(MotionChart)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 1, 1, 1)
        self.sizeCombo = QtGui.QComboBox(MotionChart)
        self.sizeCombo.setObjectName(_fromUtf8("sizeCombo"))
        self.gridLayout_2.addWidget(self.sizeCombo, 4, 1, 1, 1)
        self.entityCheckGroup = QtGui.QGroupBox(MotionChart)
        self.entityCheckGroup.setMinimumSize(QtCore.QSize(0, 150))
        self.entityCheckGroup.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.entityCheckGroup.setObjectName(_fromUtf8("entityCheckGroup"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.entityCheckGroup)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scrollArea = QtGui.QScrollArea(self.entityCheckGroup)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 121, 228))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.entityLayout = QtGui.QVBoxLayout()
        self.entityLayout.setObjectName(_fromUtf8("entityLayout"))
        self.checkBox = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.entityLayout.addWidget(self.checkBox)
        self.verticalLayout_6.addLayout(self.entityLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.gridLayout_2.addWidget(self.entityCheckGroup, 5, 1, 2, 1)

        self.retranslateUi(MotionChart)
        self.plotTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MotionChart)

    def retranslateUi(self, MotionChart):
        MotionChart.setWindowTitle(QtGui.QApplication.translate("MotionChart", "Motion Chart", None, QtGui.QApplication.UnicodeUTF8))
        self.yLog.setText(QtGui.QApplication.translate("MotionChart", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.scatter), QtGui.QApplication.translate("MotionChart", "Scatter Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.plotTabWidget.setTabToolTip(self.plotTabWidget.indexOf(self.scatter), QtGui.QApplication.translate("MotionChart", "Scatter plot", None, QtGui.QApplication.UnicodeUTF8))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.histogram), QtGui.QApplication.translate("MotionChart", "Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.plotTabWidget.setTabToolTip(self.plotTabWidget.indexOf(self.histogram), QtGui.QApplication.translate("MotionChart", "Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.lines), QtGui.QApplication.translate("MotionChart", "Line Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.plotTabWidget.setTabToolTip(self.plotTabWidget.indexOf(self.lines), QtGui.QApplication.translate("MotionChart", "Line plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MotionChart", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.xLog.setText(QtGui.QApplication.translate("MotionChart", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLabel.setText(QtGui.QApplication.translate("MotionChart", "time", None, QtGui.QApplication.UnicodeUTF8))
        self.playButton.setToolTip(QtGui.QApplication.translate("MotionChart", "Play/Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.playSpeed.setToolTip(QtGui.QApplication.translate("MotionChart", "Playback speed (frames/sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSlider.setToolTip(QtGui.QApplication.translate("MotionChart", "Time slider", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSlider.setWhatsThis(QtGui.QApplication.translate("MotionChart", "Move this to se data at a certain point in time.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MotionChart", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.entityCheckGroup.setTitle(QtGui.QApplication.translate("MotionChart", "Entities", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MotionChart", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MotionChart = QtGui.QWidget()
    ui = Ui_MotionChart()
    ui.setupUi(MotionChart)
    MotionChart.show()
    sys.exit(app.exec_())

