__version__ = "0.3.8"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '91914523b0cd3edf28a3545beecd0a2129e2ad0e'
__git_head_subject__ = 'Finished release v0.3.8.'
__git_head_message__ = '* release/v0.3.8:\n  HOSTDEV-594 adding shrink-cache-dist option to the recipe configuration\n  empty commit after version v0.3.7'
__git_dirty_diff__ = ''