
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1b1'
version_full = '43d736b99d4590a8d1a5d94d313d9fcf2f7ced27'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

