__version__ = "0.2.5-develop-32-g0fbf6b0"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = 'develop'
__git_remote_tracking_branch__ = 'origin/develop'
__git_remote_url__ = 'git@gitserver:/host/infi-recipe-application-packager.git'
__git_head_hash__ = '0fbf6b0a5c4d7b182ee21370b8a877a91f948464'
__git_head_subject__ = 'HIP-381 postuninstall script in rpmspec will be executed only on removal, not upgrade'
__git_head_message__ = ''
__git_dirty_diff__ = ''