# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MicroscopeUpload.ui'
#
# Created: Tue Jul 31 04:19:55 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Upload(object):
    def setupUi(self, Upload):
        Upload.setObjectName(_fromUtf8("Upload"))
        Upload.resize(700, 850)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Upload.sizePolicy().hasHeightForWidth())
        Upload.setSizePolicy(sizePolicy)
        Upload.setMinimumSize(QtCore.QSize(700, 0))
        Upload.setMaximumSize(QtCore.QSize(650, 16777215))
        Upload.setAutoFillBackground(False)
        Upload.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(Upload)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.grid_Status = QtGui.QGridLayout()
        self.grid_Status.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.grid_Status.setObjectName(_fromUtf8("grid_Status"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_session = QtGui.QLabel(self.centralwidget)
        self.label_session.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_session.setText(_fromUtf8(""))
        self.label_session.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_session.setOpenExternalLinks(True)
        self.label_session.setObjectName(_fromUtf8("label_session"))
        self.horizontalLayout_10.addWidget(self.label_session)
        self.label_user = QtGui.QLabel(self.centralwidget)
        self.label_user.setText(_fromUtf8(""))
        self.label_user.setObjectName(_fromUtf8("label_user"))
        self.horizontalLayout_10.addWidget(self.label_user)
        self.grid_Status.addLayout(self.horizontalLayout_10, 1, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(20, 23))
        self.label_15.setMaximumSize(QtCore.QSize(1000, 23))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.grid_Status.addWidget(self.label_15, 4, 0, 1, 1)
        self.label_project = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_project.sizePolicy().hasHeightForWidth())
        self.label_project.setSizePolicy(sizePolicy)
        self.label_project.setText(_fromUtf8(""))
        self.label_project.setOpenExternalLinks(True)
        self.label_project.setObjectName(_fromUtf8("label_project"))
        self.grid_Status.addWidget(self.label_project, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(20, 23))
        self.label_14.setMaximumSize(QtCore.QSize(1000, 23))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.grid_Status.addWidget(self.label_14, 5, 0, 1, 1)
        self.label_freeze = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_freeze.sizePolicy().hasHeightForWidth())
        self.label_freeze.setSizePolicy(sizePolicy)
        self.label_freeze.setText(_fromUtf8(""))
        self.label_freeze.setOpenExternalLinks(True)
        self.label_freeze.setObjectName(_fromUtf8("label_freeze"))
        self.grid_Status.addWidget(self.label_freeze, 5, 1, 1, 1)
        self.button_session = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_session.sizePolicy().hasHeightForWidth())
        self.button_session.setSizePolicy(sizePolicy)
        self.button_session.setMinimumSize(QtCore.QSize(90, 0))
        self.button_session.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.button_session.setArrowType(QtCore.Qt.NoArrow)
        self.button_session.setObjectName(_fromUtf8("button_session"))
        self.grid_Status.addWidget(self.button_session, 1, 0, 1, 1)
        self.button_grid = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_grid.sizePolicy().hasHeightForWidth())
        self.button_grid.setSizePolicy(sizePolicy)
        self.button_grid.setMinimumSize(QtCore.QSize(90, 0))
        self.button_grid.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.button_grid.setObjectName(_fromUtf8("button_grid"))
        self.grid_Status.addWidget(self.button_grid, 2, 0, 1, 1)
        self.label_grid = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_grid.sizePolicy().hasHeightForWidth())
        self.label_grid.setSizePolicy(sizePolicy)
        self.label_grid.setText(_fromUtf8(""))
        self.label_grid.setOpenExternalLinks(True)
        self.label_grid.setObjectName(_fromUtf8("label_grid"))
        self.grid_Status.addWidget(self.label_grid, 2, 1, 1, 1)
        self.button_path = QtGui.QToolButton(self.centralwidget)
        self.button_path.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_path.sizePolicy().hasHeightForWidth())
        self.button_path.setSizePolicy(sizePolicy)
        self.button_path.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.button_path.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.button_path.setArrowType(QtCore.Qt.NoArrow)
        self.button_path.setObjectName(_fromUtf8("button_path"))
        self.grid_Status.addWidget(self.button_path, 3, 0, 1, 1)
        self.label_path = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_path.sizePolicy().hasHeightForWidth())
        self.label_path.setSizePolicy(sizePolicy)
        self.label_path.setText(_fromUtf8(""))
        self.label_path.setObjectName(_fromUtf8("label_path"))
        self.grid_Status.addWidget(self.label_path, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.grid_Status)
        self.layout_Comments = QtGui.QVBoxLayout()
        self.layout_Comments.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.layout_Comments.setObjectName(_fromUtf8("layout_Comments"))
        self.browser_comments = QtGui.QTextBrowser(self.centralwidget)
        self.browser_comments.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browser_comments.sizePolicy().hasHeightForWidth())
        self.browser_comments.setSizePolicy(sizePolicy)
        self.browser_comments.setMaximumSize(QtCore.QSize(16777215, 100))
        self.browser_comments.setFrameShape(QtGui.QFrame.StyledPanel)
        self.browser_comments.setFrameShadow(QtGui.QFrame.Sunken)
        self.browser_comments.setOpenExternalLinks(True)
        self.browser_comments.setObjectName(_fromUtf8("browser_comments"))
        self.layout_Comments.addWidget(self.browser_comments)
        self.edit_addcomment = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_addcomment.sizePolicy().hasHeightForWidth())
        self.edit_addcomment.setSizePolicy(sizePolicy)
        self.edit_addcomment.setMaximumSize(QtCore.QSize(16777215, 30))
        self.edit_addcomment.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.edit_addcomment.setTabChangesFocus(True)
        self.edit_addcomment.setObjectName(_fromUtf8("edit_addcomment"))
        self.layout_Comments.addWidget(self.edit_addcomment)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_addcomment = QtGui.QToolButton(self.centralwidget)
        self.button_addcomment.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.button_addcomment.setAutoRaise(False)
        self.button_addcomment.setObjectName(_fromUtf8("button_addcomment"))
        self.horizontalLayout.addWidget(self.button_addcomment)
        self.layout_Comments.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.layout_Comments)
        self.frame_settings = QtGui.QTabWidget(self.centralwidget)
        self.frame_settings.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_settings.sizePolicy().hasHeightForWidth())
        self.frame_settings.setSizePolicy(sizePolicy)
        self.frame_settings.setObjectName(_fromUtf8("frame_settings"))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabWidgetPage1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.assess_ice_comments = QtGui.QComboBox(self.tabWidgetPage1)
        self.assess_ice_comments.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assess_ice_comments.sizePolicy().hasHeightForWidth())
        self.assess_ice_comments.setSizePolicy(sizePolicy)
        self.assess_ice_comments.setEditable(True)
        self.assess_ice_comments.setObjectName(_fromUtf8("assess_ice_comments"))
        self.gridLayout_2.addWidget(self.assess_ice_comments, 0, 1, 1, 1)
        self.assess_ice_thick = QtGui.QComboBox(self.tabWidgetPage1)
        self.assess_ice_thick.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assess_ice_thick.sizePolicy().hasHeightForWidth())
        self.assess_ice_thick.setSizePolicy(sizePolicy)
        self.assess_ice_thick.setEditable(True)
        self.assess_ice_thick.setObjectName(_fromUtf8("assess_ice_thick"))
        self.assess_ice_thick.addItem(_fromUtf8(""))
        self.assess_ice_thick.setItemText(0, _fromUtf8(""))
        self.assess_ice_thick.addItem(_fromUtf8(""))
        self.assess_ice_thick.addItem(_fromUtf8(""))
        self.assess_ice_thick.addItem(_fromUtf8(""))
        self.assess_ice_thick.addItem(_fromUtf8(""))
        self.assess_ice_thick.addItem(_fromUtf8(""))
        self.assess_ice_thick.addItem(_fromUtf8(""))
        self.assess_ice_thick.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.assess_ice_thick, 1, 1, 1, 1)
        self.button_assess_ice_comments = QtGui.QToolButton(self.tabWidgetPage1)
        self.button_assess_ice_comments.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_assess_ice_comments.sizePolicy().hasHeightForWidth())
        self.button_assess_ice_comments.setSizePolicy(sizePolicy)
        self.button_assess_ice_comments.setObjectName(_fromUtf8("button_assess_ice_comments"))
        self.gridLayout_2.addWidget(self.button_assess_ice_comments, 0, 2, 1, 1)
        self.button_assess_ice_thick = QtGui.QToolButton(self.tabWidgetPage1)
        self.button_assess_ice_thick.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_assess_ice_thick.sizePolicy().hasHeightForWidth())
        self.button_assess_ice_thick.setSizePolicy(sizePolicy)
        self.button_assess_ice_thick.setObjectName(_fromUtf8("button_assess_ice_thick"))
        self.gridLayout_2.addWidget(self.button_assess_ice_thick, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 2, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 3, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 4, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 5, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_25 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_2.addWidget(self.label_25)
        self.slider_tem_magnification_set = QtGui.QSlider(self.tabWidgetPage1)
        self.slider_tem_magnification_set.setMaximum(200)
        self.slider_tem_magnification_set.setOrientation(QtCore.Qt.Horizontal)
        self.slider_tem_magnification_set.setTickPosition(QtGui.QSlider.NoTicks)
        self.slider_tem_magnification_set.setTickInterval(10)
        self.slider_tem_magnification_set.setObjectName(_fromUtf8("slider_tem_magnification_set"))
        self.horizontalLayout_2.addWidget(self.slider_tem_magnification_set)
        self.label_28 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_28.setMinimumSize(QtCore.QSize(25, 0))
        self.label_28.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_2.addWidget(self.label_28)
        self.edit_tem_magnification_set = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_tem_magnification_set.sizePolicy().hasHeightForWidth())
        self.edit_tem_magnification_set.setSizePolicy(sizePolicy)
        self.edit_tem_magnification_set.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edit_tem_magnification_set.setObjectName(_fromUtf8("edit_tem_magnification_set"))
        self.horizontalLayout_2.addWidget(self.edit_tem_magnification_set)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_24 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_4.addWidget(self.label_24)
        self.slider_ctf_defocus_set = QtGui.QSlider(self.tabWidgetPage1)
        self.slider_ctf_defocus_set.setMinimum(-5000)
        self.slider_ctf_defocus_set.setMaximum(5000)
        self.slider_ctf_defocus_set.setSingleStep(1)
        self.slider_ctf_defocus_set.setOrientation(QtCore.Qt.Horizontal)
        self.slider_ctf_defocus_set.setTickPosition(QtGui.QSlider.NoTicks)
        self.slider_ctf_defocus_set.setTickInterval(1000)
        self.slider_ctf_defocus_set.setObjectName(_fromUtf8("slider_ctf_defocus_set"))
        self.horizontalLayout_4.addWidget(self.slider_ctf_defocus_set)
        self.label_23 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_23.setMinimumSize(QtCore.QSize(25, 0))
        self.label_23.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_4.addWidget(self.label_23)
        self.edit_ctf_defocus_set = QtGui.QLineEdit(self.tabWidgetPage1)
        self.edit_ctf_defocus_set.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edit_ctf_defocus_set.setObjectName(_fromUtf8("edit_ctf_defocus_set"))
        self.horizontalLayout_4.addWidget(self.edit_ctf_defocus_set)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_26 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_5.addWidget(self.label_26)
        self.slider_time_exposure_tem = QtGui.QSlider(self.tabWidgetPage1)
        self.slider_time_exposure_tem.setMaximum(10000)
        self.slider_time_exposure_tem.setOrientation(QtCore.Qt.Horizontal)
        self.slider_time_exposure_tem.setTickPosition(QtGui.QSlider.NoTicks)
        self.slider_time_exposure_tem.setObjectName(_fromUtf8("slider_time_exposure_tem"))
        self.horizontalLayout_5.addWidget(self.slider_time_exposure_tem)
        self.label_29 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_29.setMinimumSize(QtCore.QSize(25, 0))
        self.label_29.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_5.addWidget(self.label_29)
        self.edit_time_exposure_tem = QtGui.QLineEdit(self.tabWidgetPage1)
        self.edit_time_exposure_tem.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edit_time_exposure_tem.setObjectName(_fromUtf8("edit_time_exposure_tem"))
        self.horizontalLayout_5.addWidget(self.edit_time_exposure_tem)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_27 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_6.addWidget(self.label_27)
        self.slider_tem_dose_rate = QtGui.QSlider(self.tabWidgetPage1)
        self.slider_tem_dose_rate.setMaximum(20000)
        self.slider_tem_dose_rate.setOrientation(QtCore.Qt.Horizontal)
        self.slider_tem_dose_rate.setTickPosition(QtGui.QSlider.NoTicks)
        self.slider_tem_dose_rate.setObjectName(_fromUtf8("slider_tem_dose_rate"))
        self.horizontalLayout_6.addWidget(self.slider_tem_dose_rate)
        self.label_30 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_30.setMinimumSize(QtCore.QSize(25, 0))
        self.label_30.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_6.addWidget(self.label_30)
        self.edit_tem_dose_rate = QtGui.QLineEdit(self.tabWidgetPage1)
        self.edit_tem_dose_rate.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edit_tem_dose_rate.setObjectName(_fromUtf8("edit_tem_dose_rate"))
        self.horizontalLayout_6.addWidget(self.edit_tem_dose_rate)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 5, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.frame_settings.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.verticalLayout.addWidget(self.frame_settings)
        self.horizontablah = QtGui.QHBoxLayout()
        self.horizontablah.setObjectName(_fromUtf8("horizontablah"))
        self.label_newmicrograph = QtGui.QLabel(self.centralwidget)
        self.label_newmicrograph.setEnabled(True)
        self.label_newmicrograph.setMinimumSize(QtCore.QSize(80, 0))
        self.label_newmicrograph.setObjectName(_fromUtf8("label_newmicrograph"))
        self.horizontablah.addWidget(self.label_newmicrograph)
        self.edit_id_micrograph = QtGui.QLineEdit(self.centralwidget)
        self.edit_id_micrograph.setEnabled(True)
        self.edit_id_micrograph.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edit_id_micrograph.setObjectName(_fromUtf8("edit_id_micrograph"))
        self.horizontablah.addWidget(self.edit_id_micrograph)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontablah.addItem(spacerItem1)
        self.button_newmicrograph = QtGui.QToolButton(self.centralwidget)
        self.button_newmicrograph.setEnabled(False)
        self.button_newmicrograph.setObjectName(_fromUtf8("button_newmicrograph"))
        self.horizontablah.addWidget(self.button_newmicrograph)
        self.verticalLayout.addLayout(self.horizontablah)
        self.tree_files = FilesView(self.centralwidget)
        self.tree_files.setEnabled(True)
        self.tree_files.setAutoScrollMargin(0)
        self.tree_files.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tree_files.setAlternatingRowColors(True)
        self.tree_files.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tree_files.setIndentation(10)
        self.tree_files.setRootIsDecorated(True)
        self.tree_files.setUniformRowHeights(True)
        self.tree_files.setItemsExpandable(True)
        self.tree_files.setExpandsOnDoubleClick(True)
        self.tree_files.setObjectName(_fromUtf8("tree_files"))
        self.tree_files.header().setVisible(True)
        self.verticalLayout.addWidget(self.tree_files)
        Upload.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Upload)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuTest = QtGui.QMenu(self.menubar)
        self.menuTest.setObjectName(_fromUtf8("menuTest"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        Upload.setMenuBar(self.menubar)
        self.actionTest = QtGui.QAction(Upload)
        self.actionTest.setObjectName(_fromUtf8("actionTest"))
        self.actionQuit = QtGui.QAction(Upload)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Upload)
        QtCore.QMetaObject.connectSlotsByName(Upload)

    def retranslateUi(self, Upload):
        Upload.setWindowTitle(QtGui.QApplication.translate("Upload", "emdash", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Upload", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Upload", "Grid Prep", None, QtGui.QApplication.UnicodeUTF8))
        self.button_session.setText(QtGui.QApplication.translate("Upload", "Session", None, QtGui.QApplication.UnicodeUTF8))
        self.button_grid.setText(QtGui.QApplication.translate("Upload", "Grid Imaging", None, QtGui.QApplication.UnicodeUTF8))
        self.button_path.setText(QtGui.QApplication.translate("Upload", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.button_addcomment.setText(QtGui.QApplication.translate("Upload", "Add Comment  ", None, QtGui.QApplication.UnicodeUTF8))
        self.assess_ice_thick.setItemText(1, QtGui.QApplication.translate("Upload", "Empty - no ice", None, QtGui.QApplication.UnicodeUTF8))
        self.assess_ice_thick.setItemText(2, QtGui.QApplication.translate("Upload", "Too thin", None, QtGui.QApplication.UnicodeUTF8))
        self.assess_ice_thick.setItemText(3, QtGui.QApplication.translate("Upload", "A little thin", None, QtGui.QApplication.UnicodeUTF8))
        self.assess_ice_thick.setItemText(4, QtGui.QApplication.translate("Upload", "Perfect", None, QtGui.QApplication.UnicodeUTF8))
        self.assess_ice_thick.setItemText(5, QtGui.QApplication.translate("Upload", "A little thick", None, QtGui.QApplication.UnicodeUTF8))
        self.assess_ice_thick.setItemText(6, QtGui.QApplication.translate("Upload", "Too thick", None, QtGui.QApplication.UnicodeUTF8))
        self.assess_ice_thick.setItemText(7, QtGui.QApplication.translate("Upload", "Bad ice", None, QtGui.QApplication.UnicodeUTF8))
        self.button_assess_ice_comments.setText(QtGui.QApplication.translate("Upload", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.button_assess_ice_thick.setText(QtGui.QApplication.translate("Upload", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Upload", "Ice Conditions", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Upload", "Intended Mag", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Upload", "Defocus", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Upload", "Exposure time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Upload", "Dose rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Upload", "x 1000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Upload", "uM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Upload", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Upload", "e/A2/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Upload", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Upload", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Upload", "over", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Upload", "under", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Upload", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Upload", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Upload", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Upload", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Upload", "Ice Thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_settings.setTabText(self.frame_settings.indexOf(self.tabWidgetPage1), QtGui.QApplication.translate("Upload", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_newmicrograph.setText(QtGui.QApplication.translate("Upload", "Next ID", None, QtGui.QApplication.UnicodeUTF8))
        self.button_newmicrograph.setText(QtGui.QApplication.translate("Upload", "New Micrograph", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTest.setTitle(QtGui.QApplication.translate("Upload", "EMDash", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("Upload", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("Upload", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("Upload", "Quit", None, QtGui.QApplication.UnicodeUTF8))

from filesview import FilesView
