# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Upload.ui'
#
# Created: Tue Jul 31 04:19:55 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Upload(object):
    def setupUi(self, Upload):
        Upload.setObjectName(_fromUtf8("Upload"))
        Upload.resize(700, 856)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Upload.sizePolicy().hasHeightForWidth())
        Upload.setSizePolicy(sizePolicy)
        Upload.setMinimumSize(QtCore.QSize(700, 0))
        Upload.setMaximumSize(QtCore.QSize(650, 16777215))
        Upload.setAutoFillBackground(False)
        Upload.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(Upload)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.grid_Status = QtGui.QGridLayout()
        self.grid_Status.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.grid_Status.setObjectName(_fromUtf8("grid_Status"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.button_grid = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_grid.sizePolicy().hasHeightForWidth())
        self.button_grid.setSizePolicy(sizePolicy)
        self.button_grid.setMinimumSize(QtCore.QSize(0, 0))
        self.button_grid.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.button_grid.setObjectName(_fromUtf8("button_grid"))
        self.horizontalLayout_8.addWidget(self.button_grid)
        self.grid_Status.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.label_grid = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_grid.sizePolicy().hasHeightForWidth())
        self.label_grid.setSizePolicy(sizePolicy)
        self.label_grid.setText(_fromUtf8(""))
        self.label_grid.setOpenExternalLinks(True)
        self.label_grid.setObjectName(_fromUtf8("label_grid"))
        self.grid_Status.addWidget(self.label_grid, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.button_path = QtGui.QToolButton(self.centralwidget)
        self.button_path.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_path.sizePolicy().hasHeightForWidth())
        self.button_path.setSizePolicy(sizePolicy)
        self.button_path.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.button_path.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.button_path.setArrowType(QtCore.Qt.NoArrow)
        self.button_path.setObjectName(_fromUtf8("button_path"))
        self.horizontalLayout.addWidget(self.button_path)
        self.grid_Status.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.button_session = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_session.sizePolicy().hasHeightForWidth())
        self.button_session.setSizePolicy(sizePolicy)
        self.button_session.setMinimumSize(QtCore.QSize(0, 0))
        self.button_session.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.button_session.setArrowType(QtCore.Qt.NoArrow)
        self.button_session.setObjectName(_fromUtf8("button_session"))
        self.horizontalLayout_7.addWidget(self.button_session)
        self.grid_Status.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_session = QtGui.QLabel(self.centralwidget)
        self.label_session.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_session.setText(_fromUtf8(""))
        self.label_session.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_session.setOpenExternalLinks(True)
        self.label_session.setObjectName(_fromUtf8("label_session"))
        self.horizontalLayout_10.addWidget(self.label_session)
        self.label_user = QtGui.QLabel(self.centralwidget)
        self.label_user.setText(_fromUtf8(""))
        self.label_user.setObjectName(_fromUtf8("label_user"))
        self.horizontalLayout_10.addWidget(self.label_user)
        self.grid_Status.addLayout(self.horizontalLayout_10, 0, 1, 1, 1)
        self.label_path = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_path.sizePolicy().hasHeightForWidth())
        self.label_path.setSizePolicy(sizePolicy)
        self.label_path.setText(_fromUtf8(""))
        self.label_path.setObjectName(_fromUtf8("label_path"))
        self.grid_Status.addWidget(self.label_path, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.grid_Status)
        self.frame_settings = QtGui.QHBoxLayout()
        self.frame_settings.setObjectName(_fromUtf8("frame_settings"))
        self.verticalLayout.addLayout(self.frame_settings)
        self.tree_files = FilesView(self.centralwidget)
        self.tree_files.setEnabled(True)
        self.tree_files.setAutoScrollMargin(0)
        self.tree_files.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tree_files.setAlternatingRowColors(True)
        self.tree_files.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tree_files.setIndentation(10)
        self.tree_files.setRootIsDecorated(True)
        self.tree_files.setUniformRowHeights(True)
        self.tree_files.setItemsExpandable(True)
        self.tree_files.setExpandsOnDoubleClick(True)
        self.tree_files.setObjectName(_fromUtf8("tree_files"))
        self.tree_files.header().setVisible(True)
        self.verticalLayout.addWidget(self.tree_files)
        Upload.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Upload)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuTest = QtGui.QMenu(self.menubar)
        self.menuTest.setObjectName(_fromUtf8("menuTest"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        Upload.setMenuBar(self.menubar)
        self.actionTest = QtGui.QAction(Upload)
        self.actionTest.setObjectName(_fromUtf8("actionTest"))
        self.actionQuit = QtGui.QAction(Upload)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Upload)
        QtCore.QMetaObject.connectSlotsByName(Upload)

    def retranslateUi(self, Upload):
        Upload.setWindowTitle(QtGui.QApplication.translate("Upload", "emdash", None, QtGui.QApplication.UnicodeUTF8))
        self.button_grid.setText(QtGui.QApplication.translate("Upload", "Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.button_path.setText(QtGui.QApplication.translate("Upload", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.button_session.setText(QtGui.QApplication.translate("Upload", "Session", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTest.setTitle(QtGui.QApplication.translate("Upload", "EMDash", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("Upload", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("Upload", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("Upload", "Quit", None, QtGui.QApplication.UnicodeUTF8))

from filesview import FilesView
