__version__ = "0.1.2"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '5a02eb13c6e67ede8e840f6aa533a0b272f741ed'
__git_head_subject__ = 'Finished release v0.1.2.'
__git_head_message__ = '* release/v0.1.2:\n  TRIVIAL skeleton update\n  empty commit after version v0.1.1'
__git_dirty_diff__ = ''