
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b']h\xfe,\xa4\xd9\xd3^\xd6\x93\x05\xb8\x02S\x89\xb6'
    
_lr_action_items = {'DIGITS':([4,],[6,]),'$end':([0,1,2,3,4,5,6,],[-1,-2,0,-3,-6,-4,-5,]),'ATOM':([0,1,3,4,5,6,],[4,4,-3,-6,-4,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formula':([0,],[1,]),'mw':([0,],[2,]),'species':([0,1,],[3,5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> mw","S'",1,None,None,None),
  ('mw -> <empty>','mw',0,'p_mw_empty','/home/nesaro/repo/pydsl_contrib/grammar/plye.py',85),
  ('mw -> formula','mw',1,'p_mw_formula','/home/nesaro/repo/pydsl_contrib/grammar/plye.py',89),
  ('formula -> species','formula',1,'p_first_species_term','/home/nesaro/repo/pydsl_contrib/grammar/plye.py',94),
  ('formula -> formula species','formula',2,'p_species_list','/home/nesaro/repo/pydsl_contrib/grammar/plye.py',98),
  ('species -> ATOM DIGITS','species',2,'p_species','/home/nesaro/repo/pydsl_contrib/grammar/plye.py',102),
  ('species -> ATOM','species',1,'p_species_default','/home/nesaro/repo/pydsl_contrib/grammar/plye.py',106),
]
