__version__ = "0.2.2"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'c68af2c91cc17112bbdd0140a5a5c13011aaeaef'
__git_head_subject__ = 'Finished release v0.2.2.'
__git_head_message__ = '* release/v0.2.2:\n  HOSTDEV-443 updated binaries\n  HOSTDEV-443\n  HOSTDEV-443\n  empty commit after version v0.2.1'
__git_dirty_diff__ = ''