
# parsetab_361960805.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '$\xee"\xc8\xd5\xcf\x99\xa7\xa4\xf9%=\x03V|)'
    
_lr_action_items = {'$end':([1,2,3,4,5,6,7,16,18,19,20,],[-5,-6,0,-14,-9,-2,-13,-12,-1,-8,-7,]),'_ANON_6':([1,2,4,5,6,7,16,17,18,19,20,],[-5,-6,12,-9,-2,-13,-12,12,-1,-8,-7,]),'_ANON_5':([1,2,5,6,7,16,18,19,20,],[-5,-6,-9,14,-13,-12,14,-8,-7,]),'_ANON_4':([1,2,5,6,7,16,18,19,20,],[-5,-6,-9,13,-13,-12,13,-8,-7,]),'_ANON_3':([0,8,9,10,11,12,13,14,15,],[7,7,7,-4,7,-3,-10,-11,7,]),'_ANON_2':([0,1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[8,-5,-6,10,-9,-2,-13,8,8,-4,8,-3,-10,-11,8,-12,10,-1,-8,-7,]),'_ANON_1':([1,2,5,6,7,16,17,18,19,20,],[-5,-6,-9,-2,-13,-12,20,-1,-8,-7,]),'_ANON_0':([0,8,9,10,11,12,13,14,15,],[9,9,9,-4,9,-3,-10,-11,9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'neg':([0,8,9,11,15,],[1,1,1,1,1,]),'number':([0,8,9,11,15,],[2,2,2,2,2,]),'start':([0,],[3,]),'add':([0,9,],[4,17,]),'atom':([0,8,9,11,15,],[5,16,5,5,19,]),'mul':([0,9,11,],[6,6,18,]),'add_symbol':([4,17,],[11,11,]),'mul_symbol':([6,18,],[15,15,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('add -> add add_symbol mul','add',3,'p_add','<string>',2),
  ('add -> mul','add',1,'p_add','<string>',3),
  ('add_symbol -> _ANON_6','add_symbol',1,'p_add_symbol','<string>',2),
  ('add_symbol -> _ANON_2','add_symbol',1,'p_add_symbol','<string>',3),
  ('atom -> neg','atom',1,'p_atom','<string>',2),
  ('atom -> number','atom',1,'p_atom','<string>',3),
  ('atom -> _ANON_0 add _ANON_1','atom',3,'p_atom','<string>',4),
  ('mul -> mul mul_symbol atom','mul',3,'p_mul','<string>',2),
  ('mul -> atom','mul',1,'p_mul','<string>',3),
  ('mul_symbol -> _ANON_4','mul_symbol',1,'p_mul_symbol','<string>',2),
  ('mul_symbol -> _ANON_5','mul_symbol',1,'p_mul_symbol','<string>',3),
  ('neg -> _ANON_2 atom','neg',2,'p_neg','<string>',2),
  ('number -> _ANON_3','number',1,'p_number','<string>',2),
  ('start -> add','start',1,'p_start','<string>',2),
]
