__version__ = "0.1.5"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'b5f12af288e25849846c591200766c1aa31cfcd2'
__git_head_subject__ = 'Finished release v0.1.5.'
__git_head_message__ = '# By Arnon Yaari (1) and Guy Rozendorn (1)\n* release/v0.1.5:\n  HIP-372 increasing sleep from 1 to 3\n  empty commit after version v0.1.4'
__git_dirty_diff__ = ''