
# This file was generated by 'versioneer.py' (0.7) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.1-dirty'
version_full = '1b9ec094993583c8ebe65a5d8fbf8ddc5cb1b67a-dirty'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

