# -*- coding: utf-8 -*-
from agx.somewhere_else.interfaces import IStubInterface
from agx.testpackage.interfaces import (
    ISomeInterface,
    IFunctionAdapter,
)
from agx.testpackage.common import AdapterBaseClass
from zope.interface import (
    Interface,
    implements,
)

class ClassAdapter(AdapterBaseClass):

    implements(ISomeInterface)

    def __init__(self, context):
        self.context = context

class ILocal(Interface):
    pass

class InterfaceAdapter(object):

    implements(ISomeInterface,IStubInterface,ILocal)

    def __init__(self, context):
        self.context = context

class TheMultiAdapter(object):

    implements(IStubInterface)

    def __init__(self, adapted, adaptedclass):
        self.adapted = adapted
        self.adaptedclass = adaptedclass

def adapter_function_module():
    raise NotImplementedError, "stub generated by AGX."