# -*- coding: utf-8 -*-
from zope.interface import (
    Interface,
    implements,
)

class SomeEvent(Interface):
    pass

class SomeClass(object):
    pass

def EventHandler(object, event):
    raise NotImplementedError, "stub generated by AGX."