__version__ = "0.4.6"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'a3789b808f5db7262aeb56e021f8af6705c7569b'
__git_head_subject__ = 'Finished release v0.4.6.'
__git_head_message__ = ''
__git_dirty_diff__ = ''