__version__ = "0.1.13"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '8f9daf34a2bbe30e38bd00eb03cf98059bd05753'
__git_head_subject__ = 'Finished release v0.1.13.'
__git_head_message__ = '# By Arnon Yaari (1) and Guy Rozendorn (1)\n* release/v0.1.13:\n  TRIVIAL skeleton update\n  empty commit after version v0.1.12'
__git_dirty_diff__ = ''