'''
Created on Jun 28, 2010

@author: brianjinwright
'''
CLOUDFILES_AUTH_USER = 'bjinwright'
CLOUDFILES_AUTH_KEY = '595aff063cc6338288cc168dcf5e663a'
CLOUDFILES_CONTAINER = 'test'
CLOUDFILES_NEW_CONTAINER = 'testb'

CLOUDFILES_B_AUTH_USER = ''
CLOUDFILES_B_AUTH_KEY = ''

CLOUDFILES_DELETE_OBJECT = ''
CLOUDFILES_DELETE_OBJECT_B = ''

