__title__ = 'testy'
__version__ = '0.1.1'
__description__ = 'Python unittest helpers adapted from Testify'
__url__ = 'https://github.com/jimr/testy'
__author__ = 'James Rutherford'
__licence__ = 'MIT'
__copyright__ = 'Copyright 2012 James Rutherford'
