__version__ = "0.3.1"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '1b48b9f27cd3cb2f87b26e3a147597a21632b428'
__git_head_subject__ = 'Finished release v0.3.1.'
__git_head_message__ = '* release/v0.3.1:\n  TRIVIAL updated README.md\n  HOSTDEV-444\n  empty commit after version v0.3'
__git_dirty_diff__ = ''