__version__ = "0.5.1"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '7b704695f6ec9f2be00522e7ee49761407b12bee'
__git_head_subject__ = 'Finished release v0.5.1.'
__git_head_message__ = '* release/v0.5.1:\n  TRIVIAL another fix for revert_if_failed\n  Freezing dependencies\n  TRIVIAL fix push changes\n  empty commit after version v0.5'
__git_dirty_diff__ = ''