__version__ = "0.4.12"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'd7fef4f810a3080402ca8c1e7159446e1740c9ee'
__git_head_subject__ = 'Finished release v0.4.12.'
__git_head_message__ = '* release/v0.4.12:\n  HOSTDEV-659 adapting to changes in pkg_resources.parse_version\n  TRIVIAL fix tests to work with new gitserver\n  empty commit after version v0.4.11'
__git_dirty_diff__ = ''