# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data/ui/qtui.ui'
#
# Created: Sat Oct 13 12:00:30 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QtMplWindow(object):
    def setupUi(self, QtMplWindow):
        QtMplWindow.setObjectName(_fromUtf8("QtMplWindow"))
        QtMplWindow.resize(800, 719)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QtMplWindow.sizePolicy().hasHeightForWidth())
        QtMplWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(QtMplWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.navigatorwidget = QtGui.QWidget(self.centralwidget)
        self.navigatorwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navigatorwidget.sizePolicy().hasHeightForWidth())
        self.navigatorwidget.setSizePolicy(sizePolicy)
        self.navigatorwidget.setMinimumSize(QtCore.QSize(92, 229))
        self.navigatorwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.navigatorwidget.setAutoFillBackground(False)
        self.navigatorwidget.setObjectName(_fromUtf8("navigatorwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.navigatorwidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self._2 = QtGui.QGridLayout()
        self._2.setSpacing(0)
        self._2.setObjectName(_fromUtf8("_2"))
        self.zoomOutButton = QtGui.QToolButton(self.navigatorwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/zoom-out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomOutButton.setIcon(icon)
        self.zoomOutButton.setObjectName(_fromUtf8("zoomOutButton"))
        self._2.addWidget(self.zoomOutButton, 5, 1, 1, 1)
        self.moveRightButton = QtGui.QToolButton(self.navigatorwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/arrow-right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveRightButton.setIcon(icon1)
        self.moveRightButton.setObjectName(_fromUtf8("moveRightButton"))
        self._2.addWidget(self.moveRightButton, 1, 2, 1, 1)
        self.moveUpButton = QtGui.QToolButton(self.navigatorwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/arrow-up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveUpButton.setIcon(icon2)
        self.moveUpButton.setObjectName(_fromUtf8("moveUpButton"))
        self._2.addWidget(self.moveUpButton, 0, 1, 1, 1)
        self.zoomSlider = QtGui.QSlider(self.navigatorwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomSlider.sizePolicy().hasHeightForWidth())
        self.zoomSlider.setSizePolicy(sizePolicy)
        self.zoomSlider.setMinimumSize(QtCore.QSize(0, 150))
        self.zoomSlider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.zoomSlider.setMinimum(0)
        self.zoomSlider.setMaximum(15)
        self.zoomSlider.setPageStep(0)
        self.zoomSlider.setProperty("value", 0)
        self.zoomSlider.setSliderPosition(0)
        self.zoomSlider.setTracking(True)
        self.zoomSlider.setOrientation(QtCore.Qt.Vertical)
        self.zoomSlider.setInvertedAppearance(False)
        self.zoomSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.zoomSlider.setTickInterval(1)
        self.zoomSlider.setObjectName(_fromUtf8("zoomSlider"))
        self._2.addWidget(self.zoomSlider, 4, 1, 1, 1)
        self.zoomInButton = QtGui.QToolButton(self.navigatorwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/zoom-in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomInButton.setIcon(icon3)
        self.zoomInButton.setObjectName(_fromUtf8("zoomInButton"))
        self._2.addWidget(self.zoomInButton, 3, 1, 1, 1)
        self.moveDownButton = QtGui.QToolButton(self.navigatorwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/arrow-down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveDownButton.setIcon(icon4)
        self.moveDownButton.setObjectName(_fromUtf8("moveDownButton"))
        self._2.addWidget(self.moveDownButton, 2, 1, 1, 1)
        self.moveLeftButton = QtGui.QToolButton(self.navigatorwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/arrow-left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveLeftButton.setIcon(icon5)
        self.moveLeftButton.setObjectName(_fromUtf8("moveLeftButton"))
        self._2.addWidget(self.moveLeftButton, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self._2)
        self.frame = QtGui.QFrame(self.navigatorwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 300))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.lonEdit = QtGui.QLineEdit(self.frame)
        self.lonEdit.setGeometry(QtCore.QRect(10, 80, 51, 21))
        self.lonEdit.setObjectName(_fromUtf8("lonEdit"))
        self.latEdit = QtGui.QLineEdit(self.frame)
        self.latEdit.setGeometry(QtCore.QRect(10, 30, 51, 21))
        self.latEdit.setObjectName(_fromUtf8("latEdit"))
        self.latLabel = QtGui.QLabel(self.frame)
        self.latLabel.setGeometry(QtCore.QRect(10, 10, 57, 15))
        self.latLabel.setObjectName(_fromUtf8("latLabel"))
        self.lonLabel = QtGui.QLabel(self.frame)
        self.lonLabel.setGeometry(QtCore.QRect(10, 60, 57, 15))
        self.lonLabel.setObjectName(_fromUtf8("lonLabel"))
        self.goLatLonButton = QtGui.QPushButton(self.frame)
        self.goLatLonButton.setGeometry(QtCore.QRect(10, 110, 51, 25))
        self.goLatLonButton.setObjectName(_fromUtf8("goLatLonButton"))
        self.line = QtGui.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 140, 91, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.lonLabel_2 = QtGui.QLabel(self.frame)
        self.lonLabel_2.setGeometry(QtCore.QRect(10, 210, 57, 15))
        self.lonLabel_2.setObjectName(_fromUtf8("lonLabel_2"))
        self.latLabel_2 = QtGui.QLabel(self.frame)
        self.latLabel_2.setGeometry(QtCore.QRect(10, 160, 57, 15))
        self.latLabel_2.setObjectName(_fromUtf8("latLabel_2"))
        self.xPosEdit = QtGui.QLineEdit(self.frame)
        self.xPosEdit.setGeometry(QtCore.QRect(10, 180, 51, 21))
        self.xPosEdit.setObjectName(_fromUtf8("xPosEdit"))
        self.yPosEdit = QtGui.QLineEdit(self.frame)
        self.yPosEdit.setGeometry(QtCore.QRect(10, 230, 51, 21))
        self.yPosEdit.setObjectName(_fromUtf8("yPosEdit"))
        self.goMatXYButton = QtGui.QPushButton(self.frame)
        self.goMatXYButton.setGeometry(QtCore.QRect(10, 260, 51, 25))
        self.goMatXYButton.setObjectName(_fromUtf8("goMatXYButton"))
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.navigatorwidget)
        self.mapwidget = QtMplWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapwidget.sizePolicy().hasHeightForWidth())
        self.mapwidget.setSizePolicy(sizePolicy)
        self.mapwidget.setObjectName(_fromUtf8("mapwidget"))
        self.horizontalLayout.addWidget(self.mapwidget)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(130, 650))
        self.frame_2.setMaximumSize(QtCore.QSize(130, 650))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.openGridButton = QtGui.QPushButton(self.frame_2)
        self.openGridButton.setObjectName(_fromUtf8("openGridButton"))
        self.verticalLayout_2.addWidget(self.openGridButton)
        self.loadChangesButton = QtGui.QPushButton(self.frame_2)
        self.loadChangesButton.setObjectName(_fromUtf8("loadChangesButton"))
        self.verticalLayout_2.addWidget(self.loadChangesButton)
        self.saveChangesButton = QtGui.QPushButton(self.frame_2)
        self.saveChangesButton.setObjectName(_fromUtf8("saveChangesButton"))
        self.verticalLayout_2.addWidget(self.saveChangesButton)
        self.line_4 = QtGui.QFrame(self.frame_2)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_2.addWidget(self.line_4)
        self.cellEditionLabel = QtGui.QLabel(self.frame_2)
        self.cellEditionLabel.setObjectName(_fromUtf8("cellEditionLabel"))
        self.verticalLayout_2.addWidget(self.cellEditionLabel)
        self.cellDepth_TLabel = QtGui.QLabel(self.frame_2)
        self.cellDepth_TLabel.setObjectName(_fromUtf8("cellDepth_TLabel"))
        self.verticalLayout_2.addWidget(self.cellDepth_TLabel)
        self.cellDepth_TEdit = QtGui.QLineEdit(self.frame_2)
        self.cellDepth_TEdit.setObjectName(_fromUtf8("cellDepth_TEdit"))
        self.verticalLayout_2.addWidget(self.cellDepth_TEdit)
        self.cellNum_LevelsLabel = QtGui.QLabel(self.frame_2)
        self.cellNum_LevelsLabel.setObjectName(_fromUtf8("cellNum_LevelsLabel"))
        self.verticalLayout_2.addWidget(self.cellNum_LevelsLabel)
        self.cellNum_LevelsEdit = QtGui.QLineEdit(self.frame_2)
        self.cellNum_LevelsEdit.setObjectName(_fromUtf8("cellNum_LevelsEdit"))
        self.verticalLayout_2.addWidget(self.cellNum_LevelsEdit)
        self.cellChangeValueButton = QtGui.QPushButton(self.frame_2)
        self.cellChangeValueButton.setObjectName(_fromUtf8("cellChangeValueButton"))
        self.verticalLayout_2.addWidget(self.cellChangeValueButton)
        self.fixedCheckBox = QtGui.QCheckBox(self.frame_2)
        self.fixedCheckBox.setObjectName(_fromUtf8("fixedCheckBox"))
        self.verticalLayout_2.addWidget(self.fixedCheckBox)
        self.line_3 = QtGui.QFrame(self.frame_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_2.addWidget(self.line_3)
        self.visualizationLabel = QtGui.QLabel(self.frame_2)
        self.visualizationLabel.setObjectName(_fromUtf8("visualizationLabel"))
        self.verticalLayout_2.addWidget(self.visualizationLabel)
        self.depthRadioButton = QtGui.QRadioButton(self.frame_2)
        self.depthRadioButton.setChecked(True)
        self.depthRadioButton.setObjectName(_fromUtf8("depthRadioButton"))
        self.verticalLayout_2.addWidget(self.depthRadioButton)
        self.levelsRadioButton = QtGui.QRadioButton(self.frame_2)
        self.levelsRadioButton.setObjectName(_fromUtf8("levelsRadioButton"))
        self.verticalLayout_2.addWidget(self.levelsRadioButton)
        self.colorbarRangeLabel = QtGui.QLabel(self.frame_2)
        self.colorbarRangeLabel.setObjectName(_fromUtf8("colorbarRangeLabel"))
        self.verticalLayout_2.addWidget(self.colorbarRangeLabel)
        self.minLabel = QtGui.QLabel(self.frame_2)
        self.minLabel.setObjectName(_fromUtf8("minLabel"))
        self.verticalLayout_2.addWidget(self.minLabel)
        self.minEdit = QtGui.QLineEdit(self.frame_2)
        self.minEdit.setObjectName(_fromUtf8("minEdit"))
        self.verticalLayout_2.addWidget(self.minEdit)
        self.maxLabel = QtGui.QLabel(self.frame_2)
        self.maxLabel.setObjectName(_fromUtf8("maxLabel"))
        self.verticalLayout_2.addWidget(self.maxLabel)
        self.maxEdit = QtGui.QLineEdit(self.frame_2)
        self.maxEdit.setObjectName(_fromUtf8("maxEdit"))
        self.verticalLayout_2.addWidget(self.maxEdit)
        self.valueRangeButton = QtGui.QPushButton(self.frame_2)
        self.valueRangeButton.setObjectName(_fromUtf8("valueRangeButton"))
        self.verticalLayout_2.addWidget(self.valueRangeButton)
        self.line_2 = QtGui.QFrame(self.frame_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_2.addWidget(self.line_2)
        self.maxLabel_2 = QtGui.QLabel(self.frame_2)
        self.maxLabel_2.setObjectName(_fromUtf8("maxLabel_2"))
        self.verticalLayout_2.addWidget(self.maxLabel_2)
        self.resolutionComboBox = QtGui.QComboBox(self.frame_2)
        self.resolutionComboBox.setObjectName(_fromUtf8("resolutionComboBox"))
        self.resolutionComboBox.addItem(_fromUtf8(""))
        self.resolutionComboBox.addItem(_fromUtf8(""))
        self.resolutionComboBox.addItem(_fromUtf8(""))
        self.resolutionComboBox.addItem(_fromUtf8(""))
        self.resolutionComboBox.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.resolutionComboBox)
        self.horizontalLayout.addWidget(self.frame_2)
        self.reportwidget = QtGui.QWidget(self.centralwidget)
        self.reportwidget.setStyleSheet(_fromUtf8(""))
        self.reportwidget.setObjectName(_fromUtf8("reportwidget"))
        self.horizontalLayout.addWidget(self.reportwidget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        QtMplWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(QtMplWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        QtMplWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(QtMplWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        QtMplWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(QtMplWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionOpenGrid = QtGui.QAction(QtMplWindow)
        self.actionOpenGrid.setObjectName(_fromUtf8("actionOpenGrid"))
        self.actionSaveGridChanges = QtGui.QAction(QtMplWindow)
        self.actionSaveGridChanges.setObjectName(_fromUtf8("actionSaveGridChanges"))
        self.actionLoadGridChanges = QtGui.QAction(QtMplWindow)
        self.actionLoadGridChanges.setObjectName(_fromUtf8("actionLoadGridChanges"))
        self.menuFile.addAction(self.actionOpenGrid)
        self.menuFile.addAction(self.actionLoadGridChanges)
        self.menuFile.addAction(self.actionSaveGridChanges)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(QtMplWindow)
        QtCore.QMetaObject.connectSlotsByName(QtMplWindow)

    def retranslateUi(self, QtMplWindow):
        QtMplWindow.setWindowTitle(QtGui.QApplication.translate("QtMplWindow", "Thalassa", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOutButton.setToolTip(QtGui.QApplication.translate("QtMplWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOutButton.setWhatsThis(QtGui.QApplication.translate("QtMplWindow", "Zoom out by pressing this button to see less detail.", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOutButton.setText(QtGui.QApplication.translate("QtMplWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOutButton.setShortcut(QtGui.QApplication.translate("QtMplWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.moveRightButton.setToolTip(QtGui.QApplication.translate("QtMplWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.moveRightButton.setWhatsThis(QtGui.QApplication.translate("QtMplWindow", "Rotates the earth clockwise around its axis.", None, QtGui.QApplication.UnicodeUTF8))
        self.moveRightButton.setText(QtGui.QApplication.translate("QtMplWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.moveUpButton.setToolTip(QtGui.QApplication.translate("QtMplWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.moveUpButton.setWhatsThis(QtGui.QApplication.translate("QtMplWindow", "Tilts the earth\'s axis towards the user.", None, QtGui.QApplication.UnicodeUTF8))
        self.moveUpButton.setText(QtGui.QApplication.translate("QtMplWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomSlider.setToolTip(QtGui.QApplication.translate("QtMplWindow", "Zoom Slider", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomSlider.setWhatsThis(QtGui.QApplication.translate("QtMplWindow", "Use this slider to adjust the zoom level of the map.", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomInButton.setToolTip(QtGui.QApplication.translate("QtMplWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomInButton.setWhatsThis(QtGui.QApplication.translate("QtMplWindow", "Zoom in by pressing this button to see more detail.", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomInButton.setText(QtGui.QApplication.translate("QtMplWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomInButton.setShortcut(QtGui.QApplication.translate("QtMplWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.moveDownButton.setToolTip(QtGui.QApplication.translate("QtMplWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.moveDownButton.setWhatsThis(QtGui.QApplication.translate("QtMplWindow", "Tilts the earth\'s axis away from the user.", None, QtGui.QApplication.UnicodeUTF8))
        self.moveDownButton.setText(QtGui.QApplication.translate("QtMplWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.moveLeftButton.setToolTip(QtGui.QApplication.translate("QtMplWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.moveLeftButton.setWhatsThis(QtGui.QApplication.translate("QtMplWindow", "Rotates the earth counterclockwise around its axis.", None, QtGui.QApplication.UnicodeUTF8))
        self.moveLeftButton.setText(QtGui.QApplication.translate("QtMplWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.latLabel.setText(QtGui.QApplication.translate("QtMplWindow", "Lat", None, QtGui.QApplication.UnicodeUTF8))
        self.lonLabel.setText(QtGui.QApplication.translate("QtMplWindow", "Lon", None, QtGui.QApplication.UnicodeUTF8))
        self.goLatLonButton.setText(QtGui.QApplication.translate("QtMplWindow", "Go!", None, QtGui.QApplication.UnicodeUTF8))
        self.lonLabel_2.setText(QtGui.QApplication.translate("QtMplWindow", "j", None, QtGui.QApplication.UnicodeUTF8))
        self.latLabel_2.setText(QtGui.QApplication.translate("QtMplWindow", "i", None, QtGui.QApplication.UnicodeUTF8))
        self.goMatXYButton.setText(QtGui.QApplication.translate("QtMplWindow", "Go!", None, QtGui.QApplication.UnicodeUTF8))
        self.openGridButton.setText(QtGui.QApplication.translate("QtMplWindow", "Open grid", None, QtGui.QApplication.UnicodeUTF8))
        self.loadChangesButton.setText(QtGui.QApplication.translate("QtMplWindow", "Load changes", None, QtGui.QApplication.UnicodeUTF8))
        self.saveChangesButton.setText(QtGui.QApplication.translate("QtMplWindow", "Save changes", None, QtGui.QApplication.UnicodeUTF8))
        self.cellEditionLabel.setText(QtGui.QApplication.translate("QtMplWindow", "Cell edition", None, QtGui.QApplication.UnicodeUTF8))
        self.cellDepth_TLabel.setText(QtGui.QApplication.translate("QtMplWindow", "depth_t", None, QtGui.QApplication.UnicodeUTF8))
        self.cellNum_LevelsLabel.setText(QtGui.QApplication.translate("QtMplWindow", "num_levels", None, QtGui.QApplication.UnicodeUTF8))
        self.cellChangeValueButton.setText(QtGui.QApplication.translate("QtMplWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedCheckBox.setText(QtGui.QApplication.translate("QtMplWindow", "Fixed Value", None, QtGui.QApplication.UnicodeUTF8))
        self.visualizationLabel.setText(QtGui.QApplication.translate("QtMplWindow", "Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.depthRadioButton.setText(QtGui.QApplication.translate("QtMplWindow", "depth_t", None, QtGui.QApplication.UnicodeUTF8))
        self.levelsRadioButton.setText(QtGui.QApplication.translate("QtMplWindow", "num_levels", None, QtGui.QApplication.UnicodeUTF8))
        self.colorbarRangeLabel.setText(QtGui.QApplication.translate("QtMplWindow", "Colorbar range", None, QtGui.QApplication.UnicodeUTF8))
        self.minLabel.setText(QtGui.QApplication.translate("QtMplWindow", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.maxLabel.setText(QtGui.QApplication.translate("QtMplWindow", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.valueRangeButton.setText(QtGui.QApplication.translate("QtMplWindow", "Go!", None, QtGui.QApplication.UnicodeUTF8))
        self.maxLabel_2.setText(QtGui.QApplication.translate("QtMplWindow", "Coastine Details", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionComboBox.setItemText(0, QtGui.QApplication.translate("QtMplWindow", "Crude", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionComboBox.setItemText(1, QtGui.QApplication.translate("QtMplWindow", "Low", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionComboBox.setItemText(2, QtGui.QApplication.translate("QtMplWindow", "Intermediate", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionComboBox.setItemText(3, QtGui.QApplication.translate("QtMplWindow", "High", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionComboBox.setItemText(4, QtGui.QApplication.translate("QtMplWindow", "Full", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("QtMplWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("QtMplWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("QtMplWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenGrid.setText(QtGui.QApplication.translate("QtMplWindow", "Open grid", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveGridChanges.setText(QtGui.QApplication.translate("QtMplWindow", "Save grid changes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadGridChanges.setText(QtGui.QApplication.translate("QtMplWindow", "Load grid changes", None, QtGui.QApplication.UnicodeUTF8))

from thalassa.ui.qtmplui import QtMplWidget
import thalassa_rc
