
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.1'
version_full = '86839ad6f4387afb7d250bf5cb3a95f03c6e1f75'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

