__version__ = "0.2.2"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'f6d45baf128fd768cdb57ed476790acae0d852ea'
__git_head_subject__ = 'empty commit after version v0.1.6'
__git_head_message__ = ''
__git_dirty_diff__ = ''