__version__ = "0.1.3-develop-1-ga568a73"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = 'develop'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'a568a73e5c256a1c020c5a526bd187560888e5c5'
__git_head_subject__ = 'add flush to MultiStream'
__git_head_message__ = ''
__git_dirty_diff__ = ''