# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_scene', [dirname(__file__)])
        except ImportError:
            import _scene
            return _scene
        if fp is not None:
            try:
                _mod = imp.load_module('_scene', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _scene = swig_import_helper()
    del swig_import_helper
else:
    import _scene
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


import region
import fieldmodule
import timesequence
import optimisation
import field
import differentialoperator
import element
import node
import stream
import fieldcache
import graphicsfilter
import graphic
import tessellation
import graphicsmaterial
class Scene(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Scene, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Scene, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _scene.new_Scene(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _scene.delete_Scene
    __del__ = lambda self : None;
    def isValid(self): return _scene.Scene_isValid(self)
    def getId(self): return _scene.Scene_getId(self)
    ATTRIBUTE_INVALID = _scene.Scene_ATTRIBUTE_INVALID
    ATTRIBUTE_IS_MANAGED = _scene.Scene_ATTRIBUTE_IS_MANAGED
    def getAttributeInteger(self, *args): return _scene.Scene_getAttributeInteger(self, *args)
    def setAttributeInteger(self, *args): return _scene.Scene_setAttributeInteger(self, *args)
    def setRegion(self, *args): return _scene.Scene_setRegion(self, *args)
    def getName(self): return _scene.Scene_getName(self)
    def setName(self, *args): return _scene.Scene_setName(self, *args)
    def getFilter(self): return _scene.Scene_getFilter(self)
    def setFilter(self, *args): return _scene.Scene_setFilter(self, *args)
Scene_swigregister = _scene.Scene_swigregister
Scene_swigregister(Scene)

# This file is compatible with both classic and new-style classes.


