# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_stream', [dirname(__file__)])
        except ImportError:
            import _stream
            return _stream
        if fp is not None:
            try:
                _mod = imp.load_module('_stream', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _stream = swig_import_helper()
    del swig_import_helper
else:
    import _stream
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class StreamResource(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StreamResource, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StreamResource, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _stream.new_StreamResource(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _stream.delete_StreamResource
    __del__ = lambda self : None;
    def isValid(self): return _stream.StreamResource_isValid(self)
    def getId(self): return _stream.StreamResource_getId(self)
StreamResource_swigregister = _stream.StreamResource_swigregister
StreamResource_swigregister(StreamResource)

class StreamResourceFile(StreamResource):
    __swig_setmethods__ = {}
    for _s in [StreamResource]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, StreamResourceFile, name, value)
    __swig_getmethods__ = {}
    for _s in [StreamResource]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, StreamResourceFile, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _stream.new_StreamResourceFile(*args)
        try: self.this.append(this)
        except: self.this = this
    def getName(self): return _stream.StreamResourceFile_getName(self)
    __swig_destroy__ = _stream.delete_StreamResourceFile
    __del__ = lambda self : None;
StreamResourceFile_swigregister = _stream.StreamResourceFile_swigregister
StreamResourceFile_swigregister(StreamResourceFile)

class StreamResourceMemory(StreamResource):
    __swig_setmethods__ = {}
    for _s in [StreamResource]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, StreamResourceMemory, name, value)
    __swig_getmethods__ = {}
    for _s in [StreamResource]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, StreamResourceMemory, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _stream.new_StreamResourceMemory(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _stream.delete_StreamResourceMemory
    __del__ = lambda self : None;
StreamResourceMemory_swigregister = _stream.StreamResourceMemory_swigregister
StreamResourceMemory_swigregister(StreamResourceMemory)

class StreamInformation(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StreamInformation, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StreamInformation, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _stream.new_StreamInformation(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _stream.delete_StreamInformation
    __del__ = lambda self : None;
    def isValid(self): return _stream.StreamInformation_isValid(self)
    def getId(self): return _stream.StreamInformation_getId(self)
    def createResourceFile(self, *args): return _stream.StreamInformation_createResourceFile(self, *args)
    def createResourceMemory(self): return _stream.StreamInformation_createResourceMemory(self)
    def createResourceMemoryBuffer(self, *args): return _stream.StreamInformation_createResourceMemoryBuffer(self, *args)
StreamInformation_swigregister = _stream.StreamInformation_swigregister
StreamInformation_swigregister(StreamInformation)

# This file is compatible with both classic and new-style classes.


