__version__ = "0.4.6"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'eb10a770545a0e8364495349efafda08f146f06d'
__git_head_subject__ = 'Finished release v0.4.6.'
__git_head_message__ = '* release/v0.4.6:\n  HOSTDEV-678 pypi_manager now has hard_install script\n  empty commit after version v0.4.5'
__git_dirty_diff__ = ''