# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\\swmmedit_dialog_.ui'
#
# Created: Fri Jan 04 20:50:31 2013
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(943, 635)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.editor = QtGui.QTextEdit(Dialog)
        self.editor.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.editor.setObjectName(_fromUtf8("editor"))
        self.horizontalLayout.addWidget(self.editor)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.addvar = QtGui.QPushButton(self.frame)
        self.addvar.setEnabled(False)
        self.addvar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.addvar.setObjectName(_fromUtf8("addvar"))
        self.gridLayout.addWidget(self.addvar, 0, 0, 1, 1)
        self.nextvar = QtGui.QLineEdit(self.frame)
        self.nextvar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.nextvar.setReadOnly(False)
        self.nextvar.setObjectName(_fromUtf8("nextvar"))
        self.gridLayout.addWidget(self.nextvar, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.update = QtGui.QPushButton(self.frame)
        self.update.setObjectName(_fromUtf8("update"))
        self.verticalLayout.addWidget(self.update)
        self.slotdisplay_cont = QtGui.QScrollArea(self.frame)
        self.slotdisplay_cont.setWidgetResizable(True)
        self.slotdisplay_cont.setObjectName(_fromUtf8("slotdisplay_cont"))
        self.scrollAreaWidgetContents = QtGui.QWidget(self.slotdisplay_cont)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 174, 490))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.slotdisplay = QtGui.QVBoxLayout()
        self.slotdisplay.setObjectName(_fromUtf8("slotdisplay"))
        self.gridLayout_3.addLayout(self.slotdisplay, 0, 0, 1, 1)
        self.slotdisplay_cont.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.slotdisplay_cont)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 0, 8, 1, 1)
        self.caltype = QtGui.QComboBox(Dialog)
        self.caltype.setObjectName(_fromUtf8("caltype"))
        self.gridLayout_4.addWidget(self.caltype, 0, 1, 1, 1)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_4.addWidget(self.line_2, 0, 7, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_4.addWidget(self.line, 0, 6, 1, 1)
        self.calfile = QtGui.QLineEdit(Dialog)
        self.calfile.setObjectName(_fromUtf8("calfile"))
        self.gridLayout_4.addWidget(self.calfile, 0, 5, 1, 1)
        self.calbutton = QtGui.QPushButton(Dialog)
        self.calbutton.setObjectName(_fromUtf8("calbutton"))
        self.gridLayout_4.addWidget(self.calbutton, 0, 4, 1, 1)
        self.calids = QtGui.QComboBox(Dialog)
        self.calids.setObjectName(_fromUtf8("calids"))
        self.gridLayout_4.addWidget(self.calids, 0, 3, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.label.setBuddy(self.caltype)
        self.label_2.setBuddy(self.calids)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.buttonBox, self.editor)
        Dialog.setTabOrder(self.editor, self.addvar)
        Dialog.setTabOrder(self.addvar, self.nextvar)
        Dialog.setTabOrder(self.nextvar, self.update)
        Dialog.setTabOrder(self.update, self.caltype)
        Dialog.setTabOrder(self.caltype, self.calids)
        Dialog.setTabOrder(self.calids, self.calbutton)
        Dialog.setTabOrder(self.calbutton, self.calfile)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.addvar.setText(QtGui.QApplication.translate("Dialog", "&Add Var:", None, QtGui.QApplication.UnicodeUTF8))
        self.nextvar.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.update.setText(QtGui.QApplication.translate("Dialog", "Update Formulas", None, QtGui.QApplication.UnicodeUTF8))
        self.calbutton.setText(QtGui.QApplication.translate("Dialog", "Select calb. data", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Cali&b:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "&Id:", None, QtGui.QApplication.UnicodeUTF8))

