__version__ = "0.1.39"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'c9660a1cd2ac4c92ae612cd9198f253ee9370d4b'
__git_head_subject__ = 'Finished release v0.1.39.'
__git_head_message__ = ''
__git_dirty_diff__ = ''