# This file is generated by /Users/buildslave/osx-10.6/nipy-bdist-mpkg-3_3/build/setup.py
# It contains system_info results at the time of building this package.
__all__ = ["get_info","show"]

lapack_info={'language': 'f77', 'libraries': ['lapack'], 'library_dirs': ['/usr/lib']}
nipy_info={}
lapack_opt_info={'define_macros': [('NO_ATLAS_INFO', 3)], 'extra_link_args': ['-Wl,-framework', '-Wl,Accelerate'], 'extra_compile_args': ['-msse3']}

def get_info(name):
    g = globals()
    return g.get(name, g.get(name + "_info", {}))

def show():
    for name,info_dict in list(globals().items()):
        if name[0] == "_" or type(info_dict) is not type({}): continue
        print((name + ":"))
        if not info_dict:
            print("  NOT AVAILABLE")
        for k,v in list(info_dict.items()):
            v = str(v)
            if k == "sources" and len(v) > 200:
                v = v[:60] + " ...\n... " + v[-60:]
            print(("    %s = %s" % (k,v)))
    