__version__ = "0.4.10"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '1f07e45b709fef8562138cd4efa45607a3112e23'
__git_head_subject__ = 'Finished release v0.4.10.'
__git_head_message__ = '* release/v0.4.10:\n  TRIVIAL homepage\n  TRIVIAL updated skeleton\n  empty commit after version v0.4.9'
__git_dirty_diff__ = ''