
# This file was generated by 'versioneer.py' (0.7) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.11'
version_full = '04bb9975b35f4c5b0913603b08ffcc412a703235'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

