#Autogenerated in astropysics setup.py on 2012-12-07 10:24:36.028398
#these components can be changed for new versions
version = '0.1.dev-r1178'

major = 0
minor = 1
bugfix = None
dev = True

release = not dev
