__version__ = "0.3.15"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'd6382e93597dd52696b0e157cbbec8f616a340a1'
__git_head_subject__ = 'TRIVIAL switching to latest buildout'
__git_head_message__ = ''
__git_dirty_diff__ = ''