
# parsetab_2931315180.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'W;U\x1c\xa8\xb1\xe6\x05\x1f\xc0\xe5U\xbc\xc8\xde\x86'
    
_lr_action_items = {'NAME':([2,5,8,],[3,7,9,]),'COMMA':([3,4,7,],[-1,5,-2,]),'MUL':([5,],[8,]),'$end':([1,6,10,],[0,-4,-3,]),'_ANON_1':([0,],[2,]),'_ANON_0':([3,4,7,9,],[-1,6,-2,10,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'name_list':([2,],[4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('name_list -> NAME','name_list',1,'p_name_list','<string>',2),
  ('name_list -> name_list COMMA NAME','name_list',3,'p_name_list','<string>',3),
  ('start -> _ANON_1 name_list COMMA MUL NAME _ANON_0','start',6,'p_start','<string>',2),
  ('start -> _ANON_1 name_list _ANON_0','start',3,'p_start','<string>',3),
]
