__version__ = "0.1.3"
__git_commiter_name__ = "wiggin15"
__git_commiter_email__ = "wiggin15@yahoo.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '6c50842951b36e05490fa75eff69b12af6dc72fe'
__git_head_subject__ = 'Finished release v0.1.3.'
__git_head_message__ = ''
__git_dirty_diff__ = ''