# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_gtm', [dirname(__file__)])
        except ImportError:
            import _gtm
            return _gtm
        if fp is not None:
            try:
                _mod = imp.load_module('_gtm', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _gtm = swig_import_helper()
    del swig_import_helper
else:
    import _gtm
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


import operator

maxMessageLength = _gtm.maxMessageLength
maxValueLength = _gtm.maxValueLength
class GTM(_object):
    """Proxy of C++ GTM class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GTM, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GTM, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(GTM self) -> GTM"""
        this = _gtm.new_GTM()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _gtm.delete_GTM
    __del__ = lambda self : None;
    def version(self):
        """version(GTM self) -> char const *"""
        return _gtm.GTM_version(self)

    def about(self):
        """about(GTM self) -> char const *"""
        return _gtm.GTM_about(self)

    def set(self, *args):
        """
        set(GTM self, gtm_char_t const * nameOfGlobal, gtm_char_t const * valueOfGlobal, gtm_char_t * errorMessage)
        set(GTM self, std::string const & nameOfGlobal, std::string const & valueOfGlobal)
        """
        return _gtm.GTM_set(self, *args)

    def kill(self, *args):
        """
        kill(GTM self, gtm_char_t const * nameOfGlobal, gtm_char_t * errorMessage)
        kill(GTM self, std::string const & nameOfGlobal)
        """
        return _gtm.GTM_kill(self, *args)

    def lock(self, *args):
        """
        lock(GTM self, gtm_char_t const * nameOfGlobal, gtm_char_t * errorMessage)
        lock(GTM self, std::string const & nameOfGlobal)
        """
        return _gtm.GTM_lock(self, *args)

    def execute(self, *args):
        """
        execute(GTM self, gtm_char_t const * textOfCode, gtm_char_t * errorMessage)
        execute(GTM self, std::string const & textOfCode)
        """
        return _gtm.GTM_execute(self, *args)

    def get(self, *args):
        """
        get(GTM self, gtm_char_t const * nameOfGlobal, gtm_char_t * valueOfGlobal, gtm_char_t * errorMessage)
        get(GTM self, std::string const & nameOfGlobal, std::string & valueOfGlobal)
        get(GTM self, std::string const & nameOfGlobal) -> std::string
        """
        return _gtm.GTM_get(self, *args)

    def order(self, *args):
        """
        order(GTM self, gtm_char_t const * nameOfGlobal, gtm_char_t * valueOfIndex, gtm_char_t * errorMessage)
        order(GTM self, std::string const & nameOfGlobal, std::string & valueOfIndex)
        order(GTM self, std::string const & nameOfGlobal) -> std::string
        """
        return _gtm.GTM_order(self, *args)

    def query(self, *args):
        """
        query(GTM self, gtm_char_t const * nameOfGlobal, gtm_char_t * valueOfIndex, gtm_char_t * errorMessage)
        query(GTM self, std::string const & nameOfGlobal, std::string & valueOfIndex)
        query(GTM self, std::string const & nameOfGlobal) -> std::string
        """
        return _gtm.GTM_query(self, *args)

GTM_swigregister = _gtm.GTM_swigregister
GTM_swigregister(GTM)

# This file is compatible with both classic and new-style classes.


