# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ScanUpload.ui'
#
# Created: Tue Jul 31 04:19:55 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Upload(object):
    def setupUi(self, Upload):
        Upload.setObjectName(_fromUtf8("Upload"))
        Upload.resize(700, 850)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Upload.sizePolicy().hasHeightForWidth())
        Upload.setSizePolicy(sizePolicy)
        Upload.setMinimumSize(QtCore.QSize(700, 0))
        Upload.setMaximumSize(QtCore.QSize(650, 16777215))
        Upload.setAutoFillBackground(False)
        Upload.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(Upload)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.grid_Status = QtGui.QGridLayout()
        self.grid_Status.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.grid_Status.setObjectName(_fromUtf8("grid_Status"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.button_grid = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_grid.sizePolicy().hasHeightForWidth())
        self.button_grid.setSizePolicy(sizePolicy)
        self.button_grid.setMinimumSize(QtCore.QSize(0, 0))
        self.button_grid.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.button_grid.setObjectName(_fromUtf8("button_grid"))
        self.horizontalLayout_8.addWidget(self.button_grid)
        self.grid_Status.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.label_grid = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_grid.sizePolicy().hasHeightForWidth())
        self.label_grid.setSizePolicy(sizePolicy)
        self.label_grid.setText(_fromUtf8(""))
        self.label_grid.setOpenExternalLinks(True)
        self.label_grid.setObjectName(_fromUtf8("label_grid"))
        self.grid_Status.addWidget(self.label_grid, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.button_path = QtGui.QToolButton(self.centralwidget)
        self.button_path.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_path.sizePolicy().hasHeightForWidth())
        self.button_path.setSizePolicy(sizePolicy)
        self.button_path.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.button_path.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.button_path.setArrowType(QtCore.Qt.NoArrow)
        self.button_path.setObjectName(_fromUtf8("button_path"))
        self.horizontalLayout_3.addWidget(self.button_path)
        self.grid_Status.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.button_session = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_session.sizePolicy().hasHeightForWidth())
        self.button_session.setSizePolicy(sizePolicy)
        self.button_session.setMinimumSize(QtCore.QSize(0, 0))
        self.button_session.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.button_session.setArrowType(QtCore.Qt.NoArrow)
        self.button_session.setObjectName(_fromUtf8("button_session"))
        self.horizontalLayout_7.addWidget(self.button_session)
        self.grid_Status.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_session = QtGui.QLabel(self.centralwidget)
        self.label_session.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_session.setText(_fromUtf8(""))
        self.label_session.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_session.setOpenExternalLinks(True)
        self.label_session.setObjectName(_fromUtf8("label_session"))
        self.horizontalLayout_10.addWidget(self.label_session)
        self.label_user = QtGui.QLabel(self.centralwidget)
        self.label_user.setText(_fromUtf8(""))
        self.label_user.setObjectName(_fromUtf8("label_user"))
        self.horizontalLayout_10.addWidget(self.label_user)
        self.grid_Status.addLayout(self.horizontalLayout_10, 0, 1, 1, 1)
        self.label_path = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_path.sizePolicy().hasHeightForWidth())
        self.label_path.setSizePolicy(sizePolicy)
        self.label_path.setText(_fromUtf8(""))
        self.label_path.setObjectName(_fromUtf8("label_path"))
        self.grid_Status.addWidget(self.label_path, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.grid_Status)
        self.frame_settings = QtGui.QTabWidget(self.centralwidget)
        self.frame_settings.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_settings.sizePolicy().hasHeightForWidth())
        self.frame_settings.setSizePolicy(sizePolicy)
        self.frame_settings.setObjectName(_fromUtf8("frame_settings"))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabWidgetPage1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_25 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_2.addWidget(self.label_25)
        self.slider_scan_step = QtGui.QSlider(self.tabWidgetPage1)
        self.slider_scan_step.setMaximum(20000)
        self.slider_scan_step.setOrientation(QtCore.Qt.Horizontal)
        self.slider_scan_step.setTickPosition(QtGui.QSlider.NoTicks)
        self.slider_scan_step.setTickInterval(10)
        self.slider_scan_step.setObjectName(_fromUtf8("slider_scan_step"))
        self.horizontalLayout_2.addWidget(self.slider_scan_step)
        self.label_28 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_28.setMinimumSize(QtCore.QSize(25, 0))
        self.label_28.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_2.addWidget(self.label_28)
        self.edit_scan_step = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_scan_step.sizePolicy().hasHeightForWidth())
        self.edit_scan_step.setSizePolicy(sizePolicy)
        self.edit_scan_step.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edit_scan_step.setObjectName(_fromUtf8("edit_scan_step"))
        self.horizontalLayout_2.addWidget(self.edit_scan_step)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_24 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_4.addWidget(self.label_24)
        self.slider_nikon_gain = QtGui.QSlider(self.tabWidgetPage1)
        self.slider_nikon_gain.setMinimum(-2000)
        self.slider_nikon_gain.setMaximum(2000)
        self.slider_nikon_gain.setSingleStep(1)
        self.slider_nikon_gain.setOrientation(QtCore.Qt.Horizontal)
        self.slider_nikon_gain.setTickPosition(QtGui.QSlider.NoTicks)
        self.slider_nikon_gain.setTickInterval(1000)
        self.slider_nikon_gain.setObjectName(_fromUtf8("slider_nikon_gain"))
        self.horizontalLayout_4.addWidget(self.slider_nikon_gain)
        self.label_23 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_23.setMinimumSize(QtCore.QSize(25, 0))
        self.label_23.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_4.addWidget(self.label_23)
        self.edit_nikon_gain = QtGui.QLineEdit(self.tabWidgetPage1)
        self.edit_nikon_gain.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edit_nikon_gain.setObjectName(_fromUtf8("edit_nikon_gain"))
        self.horizontalLayout_4.addWidget(self.edit_nikon_gain)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 5, 1, 1, 1)
        self.edit_scanner_cartridge = QtGui.QComboBox(self.tabWidgetPage1)
        self.edit_scanner_cartridge.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_scanner_cartridge.sizePolicy().hasHeightForWidth())
        self.edit_scanner_cartridge.setSizePolicy(sizePolicy)
        self.edit_scanner_cartridge.setEditable(True)
        self.edit_scanner_cartridge.setObjectName(_fromUtf8("edit_scanner_cartridge"))
        self.edit_scanner_cartridge.addItem(_fromUtf8(""))
        self.edit_scanner_cartridge.setItemText(0, _fromUtf8(""))
        self.edit_scanner_cartridge.addItem(_fromUtf8(""))
        self.edit_scanner_cartridge.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.edit_scanner_cartridge, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.edit_scanner_film = QtGui.QComboBox(self.tabWidgetPage1)
        self.edit_scanner_film.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_scanner_film.sizePolicy().hasHeightForWidth())
        self.edit_scanner_film.setSizePolicy(sizePolicy)
        self.edit_scanner_film.setEditable(True)
        self.edit_scanner_film.setObjectName(_fromUtf8("edit_scanner_film"))
        self.edit_scanner_film.addItem(_fromUtf8(""))
        self.edit_scanner_film.setItemText(0, _fromUtf8(""))
        self.edit_scanner_film.addItem(_fromUtf8(""))
        self.edit_scanner_film.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.edit_scanner_film, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_27 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_6.addWidget(self.label_27)
        self.slider_angstroms_per_pixel = QtGui.QSlider(self.tabWidgetPage1)
        self.slider_angstroms_per_pixel.setMaximum(20000)
        self.slider_angstroms_per_pixel.setOrientation(QtCore.Qt.Horizontal)
        self.slider_angstroms_per_pixel.setTickPosition(QtGui.QSlider.NoTicks)
        self.slider_angstroms_per_pixel.setObjectName(_fromUtf8("slider_angstroms_per_pixel"))
        self.horizontalLayout_6.addWidget(self.slider_angstroms_per_pixel)
        self.label_30 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_30.setMinimumSize(QtCore.QSize(25, 0))
        self.label_30.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_6.addWidget(self.label_30)
        self.edit_angstroms_per_pixel = QtGui.QLineEdit(self.tabWidgetPage1)
        self.edit_angstroms_per_pixel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edit_angstroms_per_pixel.setObjectName(_fromUtf8("edit_angstroms_per_pixel"))
        self.horizontalLayout_6.addWidget(self.edit_angstroms_per_pixel)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_26 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_5.addWidget(self.label_26)
        self.slider_scan_average = QtGui.QSlider(self.tabWidgetPage1)
        self.slider_scan_average.setMaximum(80)
        self.slider_scan_average.setOrientation(QtCore.Qt.Horizontal)
        self.slider_scan_average.setTickPosition(QtGui.QSlider.NoTicks)
        self.slider_scan_average.setObjectName(_fromUtf8("slider_scan_average"))
        self.horizontalLayout_5.addWidget(self.slider_scan_average)
        self.label_29 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_29.setMinimumSize(QtCore.QSize(25, 0))
        self.label_29.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_5.addWidget(self.label_29)
        self.edit_scan_average = QtGui.QLineEdit(self.tabWidgetPage1)
        self.edit_scan_average.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edit_scan_average.setObjectName(_fromUtf8("edit_scan_average"))
        self.horizontalLayout_5.addWidget(self.edit_scan_average)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        self.frame_settings.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.verticalLayout.addWidget(self.frame_settings)
        self.tree_files = FilesView(self.centralwidget)
        self.tree_files.setEnabled(True)
        self.tree_files.setAutoScrollMargin(0)
        self.tree_files.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tree_files.setAlternatingRowColors(True)
        self.tree_files.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tree_files.setIndentation(10)
        self.tree_files.setRootIsDecorated(True)
        self.tree_files.setUniformRowHeights(True)
        self.tree_files.setItemsExpandable(True)
        self.tree_files.setExpandsOnDoubleClick(True)
        self.tree_files.setObjectName(_fromUtf8("tree_files"))
        self.tree_files.header().setVisible(True)
        self.verticalLayout.addWidget(self.tree_files)
        Upload.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Upload)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuTest = QtGui.QMenu(self.menubar)
        self.menuTest.setObjectName(_fromUtf8("menuTest"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        Upload.setMenuBar(self.menubar)
        self.actionTest = QtGui.QAction(Upload)
        self.actionTest.setObjectName(_fromUtf8("actionTest"))
        self.actionQuit = QtGui.QAction(Upload)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Upload)
        QtCore.QMetaObject.connectSlotsByName(Upload)

    def retranslateUi(self, Upload):
        Upload.setWindowTitle(QtGui.QApplication.translate("Upload", "emdash", None, QtGui.QApplication.UnicodeUTF8))
        self.button_grid.setText(QtGui.QApplication.translate("Upload", "Grid Imaging", None, QtGui.QApplication.UnicodeUTF8))
        self.button_path.setText(QtGui.QApplication.translate("Upload", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.button_session.setText(QtGui.QApplication.translate("Upload", "Session", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Upload", "Scan Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Upload", "Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Upload", "uM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Upload", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Upload", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Upload", "-2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Upload", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_scanner_cartridge.setItemText(1, QtGui.QApplication.translate("Upload", "Holder-1", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_scanner_cartridge.setItemText(2, QtGui.QApplication.translate("Upload", "Holder-2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Upload", "Film Holder", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_scanner_film.setItemText(1, QtGui.QApplication.translate("Upload", "Nikon-1", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_scanner_film.setItemText(2, QtGui.QApplication.translate("Upload", "Nikon-2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Upload", "Scanner ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Upload", "A/Pix", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Upload", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Upload", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Upload", "Averaging", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Upload", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Upload", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_settings.setTabText(self.frame_settings.indexOf(self.tabWidgetPage1), QtGui.QApplication.translate("Upload", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTest.setTitle(QtGui.QApplication.translate("Upload", "EMDash", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("Upload", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("Upload", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("Upload", "Quit", None, QtGui.QApplication.UnicodeUTF8))

from filesview import FilesView
