__version__ = "0.1.2"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '8f1d9c67f07a0b4396b99632d4c59b36aa735faf'
__git_head_subject__ = 'empty commit after version v0.1.1'
__git_head_message__ = ''
__git_dirty_diff__ = ''