__version__ = "0.3.2"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'e7502013ecb38723bdcdd9a260f6acf6a03a780e'
__git_head_subject__ = 'Finished release v0.3.2.'
__git_head_message__ = '* release/v0.3.2:\n  TRIVIAL using latest recipe egg, switching to buildout2\n  empty commit after version v0.3.1'
__git_dirty_diff__ = ''