__version__ = "0.2.3"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '35a47d5426c0cf4e37f4d1281dcda338823e5860'
__git_head_subject__ = 'Finished release v0.2.3.'
__git_head_message__ = '* release/v0.2.3:\n  TRIVIAL fixing pre-compilation of some packages such as python-cjson\n  empty commit after version v0.2.2'
__git_dirty_diff__ = ''