# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boing/nodes/player/uiPlayer.ui'
#
# Created: Tue Sep 18 18:50:09 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_player(object):
    def setupUi(self, player):
        player.setObjectName(_fromUtf8("player"))
        player.resize(500, 450)
        player.setWindowTitle(QtGui.QApplication.translate("player", "Boing Player", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(player)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self._frame = QtGui.QFrame(self.centralwidget)
        self._frame.setFrameShape(QtGui.QFrame.NoFrame)
        self._frame.setFrameShadow(QtGui.QFrame.Plain)
        self._frame.setObjectName(_fromUtf8("_frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self._frame)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout.addWidget(self._frame)
        self.controllayout = QtGui.QHBoxLayout()
        self.controllayout.setSpacing(5)
        self.controllayout.setObjectName(_fromUtf8("controllayout"))
        self._playstop = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._playstop.sizePolicy().hasHeightForWidth())
        self._playstop.setSizePolicy(sizePolicy)
        self._playstop.setMinimumSize(QtCore.QSize(45, 45))
        self._playstop.setMaximumSize(QtCore.QSize(45, 45))
        self._playstop.setFocusPolicy(QtCore.Qt.NoFocus)
        self._playstop.setToolTip(QtGui.QApplication.translate("player", "Start playback", None, QtGui.QApplication.UnicodeUTF8))
        self._playstop.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/textures/textures/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._playstop.setIcon(icon)
        self._playstop.setIconSize(QtCore.QSize(32, 32))
        self._playstop.setShortcut(QtGui.QApplication.translate("player", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self._playstop.setObjectName(_fromUtf8("_playstop"))
        self.controllayout.addWidget(self._playstop)
        self._togglemode = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._togglemode.sizePolicy().hasHeightForWidth())
        self._togglemode.setSizePolicy(sizePolicy)
        self._togglemode.setMinimumSize(QtCore.QSize(60, 30))
        self._togglemode.setMaximumSize(QtCore.QSize(60, 30))
        self._togglemode.setFocusPolicy(QtCore.Qt.NoFocus)
        self._togglemode.setToolTip(QtGui.QApplication.translate("player", "Toggle Playlist Scroll", None, QtGui.QApplication.UnicodeUTF8))
        self._togglemode.setText(QtGui.QApplication.translate("player", "Play all", None, QtGui.QApplication.UnicodeUTF8))
        self._togglemode.setShortcut(QtGui.QApplication.translate("player", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self._togglemode.setObjectName(_fromUtf8("_togglemode"))
        self.controllayout.addWidget(self._togglemode)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.controllayout.addItem(spacerItem)
        self._speedlabel = QtGui.QLabel(self.centralwidget)
        self._speedlabel.setText(QtGui.QApplication.translate("player", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self._speedlabel.setObjectName(_fromUtf8("_speedlabel"))
        self.controllayout.addWidget(self._speedlabel)
        self._speedslider = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._speedslider.sizePolicy().hasHeightForWidth())
        self._speedslider.setSizePolicy(sizePolicy)
        self._speedslider.setMinimumSize(QtCore.QSize(80, 30))
        self._speedslider.setMaximumSize(QtCore.QSize(80, 30))
        self._speedslider.setFocusPolicy(QtCore.Qt.NoFocus)
        self._speedslider.setToolTip(QtGui.QApplication.translate("player", "Set playback speed", None, QtGui.QApplication.UnicodeUTF8))
        self._speedslider.setMaximum(9)
        self._speedslider.setOrientation(QtCore.Qt.Horizontal)
        self._speedslider.setTickPosition(QtGui.QSlider.TicksBelow)
        self._speedslider.setTickInterval(1)
        self._speedslider.setObjectName(_fromUtf8("_speedslider"))
        self.controllayout.addWidget(self._speedslider)
        self.verticalLayout.addLayout(self.controllayout)
        player.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(player)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setTitle(QtGui.QApplication.translate("player", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Playlist = QtGui.QMenu(self.menubar)
        self.menu_Playlist.setTitle(QtGui.QApplication.translate("player", "&Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Playlist.setObjectName(_fromUtf8("menu_Playlist"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setTitle(QtGui.QApplication.translate("player", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        player.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(player)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        player.setStatusBar(self.statusbar)
        self._openfiles = QtGui.QAction(player)
        self._openfiles.setText(QtGui.QApplication.translate("player", "&Open Files...", None, QtGui.QApplication.UnicodeUTF8))
        self._openfiles.setToolTip(QtGui.QApplication.translate("player", "Add files to the playlist", None, QtGui.QApplication.UnicodeUTF8))
        self._openfiles.setShortcut(QtGui.QApplication.translate("player", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self._openfiles.setObjectName(_fromUtf8("_openfiles"))
        self._opendir = QtGui.QAction(player)
        self._opendir.setText(QtGui.QApplication.translate("player", "Open &Directory...", None, QtGui.QApplication.UnicodeUTF8))
        self._opendir.setShortcut(QtGui.QApplication.translate("player", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self._opendir.setObjectName(_fromUtf8("_opendir"))
        self._importplaylist = QtGui.QAction(player)
        self._importplaylist.setText(QtGui.QApplication.translate("player", "Import &Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self._importplaylist.setToolTip(QtGui.QApplication.translate("player", "Import a stored playlist", None, QtGui.QApplication.UnicodeUTF8))
        self._importplaylist.setShortcut(QtGui.QApplication.translate("player", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self._importplaylist.setObjectName(_fromUtf8("_importplaylist"))
        self._saveplaylist = QtGui.QAction(player)
        self._saveplaylist.setText(QtGui.QApplication.translate("player", "&Save Playlist to File...", None, QtGui.QApplication.UnicodeUTF8))
        self._saveplaylist.setToolTip(QtGui.QApplication.translate("player", "Save Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self._saveplaylist.setShortcut(QtGui.QApplication.translate("player", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self._saveplaylist.setObjectName(_fromUtf8("_saveplaylist"))
        self._quit = QtGui.QAction(player)
        self._quit.setText(QtGui.QApplication.translate("player", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self._quit.setShortcut(QtGui.QApplication.translate("player", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self._quit.setObjectName(_fromUtf8("_quit"))
        self._createfolder = QtGui.QAction(player)
        self._createfolder.setText(QtGui.QApplication.translate("player", "Create &Folder", None, QtGui.QApplication.UnicodeUTF8))
        self._createfolder.setToolTip(QtGui.QApplication.translate("player", "Create a new folder", None, QtGui.QApplication.UnicodeUTF8))
        self._createfolder.setShortcut(QtGui.QApplication.translate("player", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self._createfolder.setObjectName(_fromUtf8("_createfolder"))
        self._clear = QtGui.QAction(player)
        self._clear.setText(QtGui.QApplication.translate("player", "&Clear Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self._clear.setObjectName(_fromUtf8("_clear"))
        self._about = QtGui.QAction(player)
        self._about.setText(QtGui.QApplication.translate("player", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self._about.setObjectName(_fromUtf8("_about"))
        self.menu_File.addAction(self._openfiles)
        self.menu_File.addAction(self._opendir)
        self.menu_File.addAction(self._importplaylist)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self._saveplaylist)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self._quit)
        self.menu_Playlist.addAction(self._createfolder)
        self.menu_Playlist.addAction(self._clear)
        self.menu_Help.addAction(self._about)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Playlist.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(player)
        QtCore.QObject.connect(self._quit, QtCore.SIGNAL(_fromUtf8("triggered()")), player.close)
        QtCore.QMetaObject.connectSlotsByName(player)

    def retranslateUi(self, player):
        pass

