__version__ = "0.3.14"
__git_commiter_name__ = "wiggin15"
__git_commiter_email__ = "wiggin15@yahoo.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '956949548c4870afdf227914ea613e177949f4b6'
__git_head_subject__ = 'fix tests - lxml package version'
__git_head_message__ = ''
__git_dirty_diff__ = ''