# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
import _ictclasing
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ictclasing', [dirname(__file__)])
        except ImportError:
            import _ictclasing
            return _ictclasing
        if fp is not None:
            try:
                _mod = imp.load_module('_ictclasing', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ictclasing = swig_import_helper()
    del swig_import_helper
else:
    import _ictclasing
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def testICTCLAS_ParagraphProcess(*args):
  return _ictclasing.testICTCLAS_ParagraphProcess(*args)
testICTCLAS_ParagraphProcess = _ictclasing.testICTCLAS_ParagraphProcess

def addItem(*args):
  return _ictclasing.addItem(*args)
addItem = _ictclasing.addItem

def delItem(*args):
  return _ictclasing.delItem(*args)
delItem = _ictclasing.delItem

def loadDict(*args):
  return _ictclasing.loadDict(*args)
loadDict = _ictclasing.loadDict

def saveDict(*args):
  return _ictclasing.saveDict(*args)
saveDict = _ictclasing.saveDict
# This file is compatible with both classic and new-style classes.


