# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Tue Jan 15 14:49:24 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 576)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, 9, 781, 541))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.line = QtGui.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(230, 10, 20, 511))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayoutWidget = QtGui.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(260, 10, 511, 511))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.movie_imdb_id = QtGui.QLineEdit(self.gridLayoutWidget)
        self.movie_imdb_id.setObjectName("movie_imdb_id")
        self.gridLayout.addWidget(self.movie_imdb_id, 6, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 1, 1, 1)
        self.movie_genre = QtGui.QLineEdit(self.gridLayoutWidget)
        self.movie_genre.setObjectName("movie_genre")
        self.gridLayout.addWidget(self.movie_genre, 2, 4, 1, 1)
        self.movie_plot = QtGui.QPlainTextEdit(self.gridLayoutWidget)
        self.movie_plot.setObjectName("movie_plot")
        self.gridLayout.addWidget(self.movie_plot, 5, 2, 1, 3)
        self.movie_release = QtGui.QLineEdit(self.gridLayoutWidget)
        self.movie_release.setObjectName("movie_release")
        self.gridLayout.addWidget(self.movie_release, 2, 2, 1, 1)
        self.movie_actor_list = QtGui.QPlainTextEdit(self.gridLayoutWidget)
        self.movie_actor_list.setObjectName("movie_actor_list")
        self.gridLayout.addWidget(self.movie_actor_list, 4, 2, 1, 3)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.movie_rating = QtGui.QLineEdit(self.gridLayoutWidget)
        self.movie_rating.setObjectName("movie_rating")
        self.gridLayout.addWidget(self.movie_rating, 7, 2, 1, 1)
        self.movie_imdb_url = QtGui.QLineEdit(self.gridLayoutWidget)
        self.movie_imdb_url.setObjectName("movie_imdb_url")
        self.gridLayout.addWidget(self.movie_imdb_url, 6, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 1, 1, 1)
        self.movie_director = QtGui.QLineEdit(self.gridLayoutWidget)
        self.movie_director.setObjectName("movie_director")
        self.gridLayout.addWidget(self.movie_director, 1, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 3, 1, 1)
        self.movie_language = QtGui.QLineEdit(self.gridLayoutWidget)
        self.movie_language.setObjectName("movie_language")
        self.gridLayout.addWidget(self.movie_language, 1, 4, 1, 1)
        self.movie_length = QtGui.QLineEdit(self.gridLayoutWidget)
        self.movie_length.setObjectName("movie_length")
        self.gridLayout.addWidget(self.movie_length, 7, 4, 1, 1)
        self.movie_name = QtGui.QLineEdit(self.gridLayoutWidget)
        self.movie_name.setObjectName("movie_name")
        self.gridLayout.addWidget(self.movie_name, 0, 2, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imdb_search = QtGui.QPushButton(self.gridLayoutWidget)
        self.imdb_search.setAutoDefault(True)
        self.imdb_search.setDefault(True)
        self.imdb_search.setObjectName("imdb_search")
        self.horizontalLayout.addWidget(self.imdb_search)
        self.save = QtGui.QPushButton(self.gridLayoutWidget)
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 4, 1, 1)
        self.webView = QtWebKit.QWebView(self.gridLayoutWidget)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setZoomFactor(2.0)
        self.webView.setObjectName("webView")
        self.gridLayout.addWidget(self.webView, 8, 1, 1, 4)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(9, 469, 221, 54))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_movie = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.add_movie.setObjectName("add_movie")
        self.gridLayout_2.addWidget(self.add_movie, 0, 0, 1, 1)
        self.delete_movie = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.delete_movie.setObjectName("delete_movie")
        self.gridLayout_2.addWidget(self.delete_movie, 0, 1, 1, 1)
        self.play_movie = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.play_movie.setObjectName("play_movie")
        self.gridLayout_2.addWidget(self.play_movie, 1, 0, 1, 1)
        self.about = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.about.setObjectName("about")
        self.gridLayout_2.addWidget(self.about, 1, 1, 1, 1)
        self.listWidget = QtGui.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(5, 41, 221, 421))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.frame)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 0, 221, 41))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.search = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.search.setAutoDefault(True)
        self.search.setObjectName("search")
        self.gridLayout_3.addWidget(self.search, 0, 1, 1, 1)
        self.search_text = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.search_text.setObjectName("search_text")
        self.gridLayout_3.addWidget(self.search_text, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Personal Movie Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "IMDB URL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "IMDB Id:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Genre:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Movie Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Year of Release:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Actors:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Rating:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Director:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Language:", None, QtGui.QApplication.UnicodeUTF8))
        self.imdb_search.setText(QtGui.QApplication.translate("MainWindow", "IMDB Search", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.add_movie.setText(QtGui.QApplication.translate("MainWindow", "Add a movie", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_movie.setText(QtGui.QApplication.translate("MainWindow", "Delete Movie", None, QtGui.QApplication.UnicodeUTF8))
        self.play_movie.setText(QtGui.QApplication.translate("MainWindow", "Play Movie", None, QtGui.QApplication.UnicodeUTF8))
        self.about.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.search.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit
