__version__ = "0.3.5"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'ce4dc5d73b6e4d3bf1086ee23e4a3d7c5ceb65e7'
__git_head_subject__ = 'Finished release v0.3.5.'
__git_head_message__ = "* release/v0.3.5:\n  HOSTDEV-579 version string fix\\n\\nreplacing '-' with '_'\n  empty commit after version v0.3.4"
__git_dirty_diff__ = ''