__version__ = "0.1.16"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '75a94726108ca0c23df9980d2d02d63dad9c5570'
__git_head_subject__ = 'Finished release v0.1.16.'
__git_head_message__ = ''
__git_dirty_diff__ = ''