# Copyright (c) by it's authors. 
# Some rights reserved. See LICENSE, AUTHORS.

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/dominik/Documents/Projekte/wallaby/wallaby-app-inspector/wallaby/apps/inspector/mainWindow.ui'
#
# Created: Sun Dec 16 18:13:55 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1265, 720)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setMargin(12)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tabs_2 = Tabs(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(66)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs_2.sizePolicy().hasHeightForWidth())
        self.tabs_2.setSizePolicy(sizePolicy)
        self.tabs_2.setTabPosition(QtGui.QTabWidget.South)
        self.tabs_2.setDocumentMode(True)
        self.tabs_2.setObjectName(_fromUtf8("tabs_2"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setSpacing(-1)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.widget_2 = QtGui.QWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(33)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setSpacing(-1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget_3 = QtGui.QWidget(self.widget_2)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setSpacing(-1)
        self.horizontalLayout_2.setMargin(6)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.actionButton_2 = ActionButton(self.widget_3)
        self.actionButton_2.setObjectName(_fromUtf8("actionButton_2"))
        self.horizontalLayout_2.addWidget(self.actionButton_2)
        self.actionButton_3 = ActionButton(self.widget_3)
        self.actionButton_3.setObjectName(_fromUtf8("actionButton_3"))
        self.horizontalLayout_2.addWidget(self.actionButton_3)
        self.actionButton = ActionButton(self.widget_3)
        self.actionButton.setObjectName(_fromUtf8("actionButton"))
        self.horizontalLayout_2.addWidget(self.actionButton)
        self.actionButton_4 = ActionButton(self.widget_3)
        self.actionButton_4.setObjectName(_fromUtf8("actionButton_4"))
        self.horizontalLayout_2.addWidget(self.actionButton_4)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widgetList = EmbeddedViewTable(self.widget_2)
        self.widgetList.setObjectName(_fromUtf8("widgetList"))
        self.verticalLayout_2.addWidget(self.widgetList)
        self.actionButton_5 = ActionButton(self.widget_2)
        self.actionButton_5.setObjectName(_fromUtf8("actionButton_5"))
        self.verticalLayout_2.addWidget(self.actionButton_5)
        self.horizontalLayout_3.addWidget(self.widget_2)
        self.tabs = Tabs(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(66)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 789, 618))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.stacked = Stacked(self.scrollAreaWidgetContents)
        self.stacked.setObjectName(_fromUtf8("stacked"))
        self.verticalLayout_4.addWidget(self.stacked)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.widget)
        self.tabs.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.embeddedViewTable = EmbeddedViewTable(self.tab_3)
        self.embeddedViewTable.setObjectName(_fromUtf8("embeddedViewTable"))
        self.verticalLayout_3.addWidget(self.embeddedViewTable)
        self.tabs.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout = QtGui.QGridLayout(self.tab_5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textPopupButton = TextPopupButton(self.tab_5)
        self.textPopupButton.setObjectName(_fromUtf8("textPopupButton"))
        self.gridLayout.addWidget(self.textPopupButton, 7, 0, 1, 1)
        self.dateEdit = DateEdit(self.tab_5)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.gridLayout.addWidget(self.dateEdit, 10, 0, 1, 1)
        self.multiViewTable = MultiViewTable(self.tab_5)
        self.multiViewTable.setObjectName(_fromUtf8("multiViewTable"))
        self.gridLayout.addWidget(self.multiViewTable, 2, 0, 1, 1)
        self.valueButton = ValueButton(self.tab_5)
        self.valueButton.setObjectName(_fromUtf8("valueButton"))
        self.gridLayout.addWidget(self.valueButton, 9, 0, 1, 1)
        self.labelTest = Label(self.tab_5)
        self.labelTest.setObjectName(_fromUtf8("labelTest"))
        self.gridLayout.addWidget(self.labelTest, 0, 0, 1, 1)
        self.Slider = Slider(self.tab_5)
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setObjectName(_fromUtf8("Slider"))
        self.gridLayout.addWidget(self.Slider, 10, 1, 1, 1)
        self.toggleButton = ToggleButton(self.tab_5)
        self.toggleButton.setObjectName(_fromUtf8("toggleButton"))
        self.gridLayout.addWidget(self.toggleButton, 7, 1, 1, 1)
        self.pushButton = PushButton(self.tab_5)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 9, 1, 1, 1)
        self.payloadLabel = PayloadLabel(self.tab_5)
        self.payloadLabel.setObjectName(_fromUtf8("payloadLabel"))
        self.gridLayout.addWidget(self.payloadLabel, 0, 1, 1, 1)
        self.imageLabel = ImageLabel(self.tab_5)
        self.imageLabel.setObjectName(_fromUtf8("imageLabel"))
        self.gridLayout.addWidget(self.imageLabel, 2, 1, 1, 1)
        self.progress = Progress(self.tab_5)
        self.progress.setObjectName(_fromUtf8("progress"))
        self.gridLayout.addWidget(self.progress, 4, 0, 1, 2)
        self.radioButton = RadioButton(self.tab_5)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout.addWidget(self.radioButton, 11, 0, 1, 1)
        self.tabs.addTab(self.tab_5, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.tabs)
        self.tabs_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_4.setSpacing(-1)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.widget_8 = QtGui.QWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(33)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_8)
        self.verticalLayout_6.setSpacing(-1)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widget_9 = QtGui.QWidget(self.widget_8)
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_9)
        self.horizontalLayout_8.setSpacing(-1)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.actionButton_10 = ActionButton(self.widget_9)
        self.actionButton_10.setObjectName(_fromUtf8("actionButton_10"))
        self.horizontalLayout_8.addWidget(self.actionButton_10)
        self.actionButton_11 = ActionButton(self.widget_9)
        self.actionButton_11.setObjectName(_fromUtf8("actionButton_11"))
        self.horizontalLayout_8.addWidget(self.actionButton_11)
        self.actionButton_12 = ActionButton(self.widget_9)
        self.actionButton_12.setObjectName(_fromUtf8("actionButton_12"))
        self.horizontalLayout_8.addWidget(self.actionButton_12)
        self.actionButton_13 = ActionButton(self.widget_9)
        self.actionButton_13.setObjectName(_fromUtf8("actionButton_13"))
        self.horizontalLayout_8.addWidget(self.actionButton_13)
        self.verticalLayout_6.addWidget(self.widget_9)
        self.embeddedViewTable_3 = EmbeddedViewTable(self.widget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(33)
        sizePolicy.setVerticalStretch(70)
        sizePolicy.setHeightForWidth(self.embeddedViewTable_3.sizePolicy().hasHeightForWidth())
        self.embeddedViewTable_3.setSizePolicy(sizePolicy)
        self.embeddedViewTable_3.setObjectName(_fromUtf8("embeddedViewTable_3"))
        self.verticalLayout_6.addWidget(self.embeddedViewTable_3)
        self.widget_4 = QtGui.QWidget(self.widget_8)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.actionButton_16 = ActionButton(self.widget_4)
        self.actionButton_16.setObjectName(_fromUtf8("actionButton_16"))
        self.horizontalLayout_10.addWidget(self.actionButton_16)
        self.actionButton_15 = ActionButton(self.widget_4)
        self.actionButton_15.setObjectName(_fromUtf8("actionButton_15"))
        self.horizontalLayout_10.addWidget(self.actionButton_15)
        self.actionButton_14 = ActionButton(self.widget_4)
        self.actionButton_14.setObjectName(_fromUtf8("actionButton_14"))
        self.horizontalLayout_10.addWidget(self.actionButton_14)
        self.verticalLayout_6.addWidget(self.widget_4)
        self.embeddedViewTable_4 = EmbeddedViewTable(self.widget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.embeddedViewTable_4.sizePolicy().hasHeightForWidth())
        self.embeddedViewTable_4.setSizePolicy(sizePolicy)
        self.embeddedViewTable_4.setObjectName(_fromUtf8("embeddedViewTable_4"))
        self.verticalLayout_6.addWidget(self.embeddedViewTable_4)
        self.horizontalLayout_4.addWidget(self.widget_8)
        self.widget_5 = QtGui.QWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(66)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setSpacing(-1)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.widget_6 = QtGui.QWidget(self.widget_5)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.actionButton_6 = ActionButton(self.widget_6)
        self.actionButton_6.setObjectName(_fromUtf8("actionButton_6"))
        self.horizontalLayout_6.addWidget(self.actionButton_6)
        self.actionButton_7 = ActionButton(self.widget_6)
        self.actionButton_7.setObjectName(_fromUtf8("actionButton_7"))
        self.horizontalLayout_6.addWidget(self.actionButton_7)
        self.verticalLayout_5.addWidget(self.widget_6)
        self.widgetList_2 = EmbeddedViewTable(self.widget_5)
        self.widgetList_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widgetList_2.setObjectName(_fromUtf8("widgetList_2"))
        self.verticalLayout_5.addWidget(self.widgetList_2)
        self.embeddedViewTable_2 = EmbeddedViewTable(self.widget_5)
        self.embeddedViewTable_2.setObjectName(_fromUtf8("embeddedViewTable_2"))
        self.verticalLayout_5.addWidget(self.embeddedViewTable_2)
        self.widget_7 = QtGui.QWidget(self.widget_5)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.actionButton_9 = ActionButton(self.widget_7)
        self.actionButton_9.setObjectName(_fromUtf8("actionButton_9"))
        self.horizontalLayout_7.addWidget(self.actionButton_9)
        self.actionButton_8 = ActionButton(self.widget_7)
        self.actionButton_8.setObjectName(_fromUtf8("actionButton_8"))
        self.horizontalLayout_7.addWidget(self.actionButton_8)
        self.verticalLayout_5.addWidget(self.widget_7)
        self.horizontalLayout_4.addWidget(self.widget_5)
        self.tabs_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.tab_6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.embeddedViewTable_5 = EmbeddedViewTable(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(33)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.embeddedViewTable_5.sizePolicy().hasHeightForWidth())
        self.embeddedViewTable_5.setSizePolicy(sizePolicy)
        self.embeddedViewTable_5.setObjectName(_fromUtf8("embeddedViewTable_5"))
        self.horizontalLayout_9.addWidget(self.embeddedViewTable_5)
        self.plainTextEdit = PlainTextEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(66)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.horizontalLayout_9.addWidget(self.plainTextEdit)
        self.tabs_2.addTab(self.tab_6, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tabs_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs_2.setCurrentIndex(0)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_2.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-main-tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_2.setText(QtGui.QApplication.translate("MainWindow", "save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_2.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_3.setText(QtGui.QApplication.translate("MainWindow", "edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_3.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton.setText(QtGui.QApplication.translate("MainWindow", "load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_4.setText(QtGui.QApplication.translate("MainWindow", "cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_4.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-rollback", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetList.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-widgets", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_5.setText(QtGui.QApplication.translate("MainWindow", "remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_5.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-widgets-remove", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-widget-tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.stacked.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-widgets-configstack", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Widget configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.embeddedViewTable.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-dict", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Generic configurator", None, QtGui.QApplication.UnicodeUTF8))
        self.textPopupButton.setText(QtGui.QApplication.translate("MainWindow", "Text - Popup", None, QtGui.QApplication.UnicodeUTF8))
        self.textPopupButton.setProperty("template", QtGui.QApplication.translate("MainWindow", "itest-textpopup", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit.setProperty("template", QtGui.QApplication.translate("MainWindow", "itest-datedit", None, QtGui.QApplication.UnicodeUTF8))
        self.multiViewTable.setProperty("template", QtGui.QApplication.translate("MainWindow", "itest-multiview", None, QtGui.QApplication.UnicodeUTF8))
        self.valueButton.setText(QtGui.QApplication.translate("MainWindow", "Value Button", None, QtGui.QApplication.UnicodeUTF8))
        self.valueButton.setProperty("template", QtGui.QApplication.translate("MainWindow", "itest-valuebutton", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTest.setText(QtGui.QApplication.translate("MainWindow", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTest.setProperty("template", QtGui.QApplication.translate("MainWindow", "itest-label", None, QtGui.QApplication.UnicodeUTF8))
        self.Slider.setProperty("template", QtGui.QApplication.translate("MainWindow", "itest-slider", None, QtGui.QApplication.UnicodeUTF8))
        self.toggleButton.setText(QtGui.QApplication.translate("MainWindow", "Toggle - Button", None, QtGui.QApplication.UnicodeUTF8))
        self.toggleButton.setProperty("template", QtGui.QApplication.translate("MainWindow", "itest-togglebutton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Push - Button", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setProperty("template", QtGui.QApplication.translate("MainWindow", "itest-pushbutton", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadLabel.setText(QtGui.QApplication.translate("MainWindow", "Payload - Label", None, QtGui.QApplication.UnicodeUTF8))
        self.payloadLabel.setProperty("template", QtGui.QApplication.translate("MainWindow", "itest-payload-table", None, QtGui.QApplication.UnicodeUTF8))
        self.imageLabel.setText(QtGui.QApplication.translate("MainWindow", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.imageLabel.setProperty("template", QtGui.QApplication.translate("MainWindow", "itest-image", None, QtGui.QApplication.UnicodeUTF8))
        self.progress.setProperty("template", QtGui.QApplication.translate("MainWindow", "itest-progress", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "Radio tet", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setProperty("template", QtGui.QApplication.translate("MainWindow", "itest-radio", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Widget Test", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_2.setTabText(self.tabs_2.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Widgets", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_10.setText(QtGui.QApplication.translate("MainWindow", "save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_10.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_11.setText(QtGui.QApplication.translate("MainWindow", "edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_11.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_12.setText(QtGui.QApplication.translate("MainWindow", "load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_12.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_13.setText(QtGui.QApplication.translate("MainWindow", "cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_13.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-rollback", None, QtGui.QApplication.UnicodeUTF8))
        self.embeddedViewTable_3.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-rooms", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_16.setText(QtGui.QApplication.translate("MainWindow", "initialize", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_16.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-rooms-initialize", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_15.setText(QtGui.QApplication.translate("MainWindow", "Suggest !", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_15.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-button-suggest", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_14.setText(QtGui.QApplication.translate("MainWindow", "remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_14.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-rooms-remove", None, QtGui.QApplication.UnicodeUTF8))
        self.embeddedViewTable_4.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-suggests", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_6.setText(QtGui.QApplication.translate("MainWindow", "add peer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_6.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-peers-add", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_7.setText(QtGui.QApplication.translate("MainWindow", "remove peer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_7.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-peers-remove", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetList_2.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-peers", None, QtGui.QApplication.UnicodeUTF8))
        self.embeddedViewTable_2.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-peers-config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_9.setText(QtGui.QApplication.translate("MainWindow", "Add peer config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_9.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-peer-config-add", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_8.setText(QtGui.QApplication.translate("MainWindow", "Remove peer config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton_8.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-peer-config-remove", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_2.setTabText(self.tabs_2.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Peers", None, QtGui.QApplication.UnicodeUTF8))
        self.embeddedViewTable_5.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-doc-rooms", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit.setProperty("template", QtGui.QApplication.translate("MainWindow", "inspector-doc-json", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_2.setTabText(self.tabs_2.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Documents", None, QtGui.QApplication.UnicodeUTF8))

from wallaby.frontends.qt.widgets.buttons.pushButton import PushButton
from wallaby.frontends.qt.widgets.multi.embeddedViewTable import EmbeddedViewTable
from wallaby.frontends.qt.widgets.labels.payloadLabel import PayloadLabel
from wallaby.frontends.qt.widgets.labels.progress import Progress
from wallaby.frontends.qt.widgets.buttons.toggleButton import ToggleButton
from wallaby.frontends.qt.widgets.multi.multiViewTable import MultiViewTable
from wallaby.frontends.qt.widgets.labels.label import Label
from wallaby.frontends.qt.widgets.edits.dateEdit import DateEdit
from wallaby.frontends.qt.widgets.buttons.radioButton import RadioButton
from wallaby.frontends.qt.widgets.containers.tabs import Tabs
from wallaby.frontends.qt.widgets.buttons.actionButton import ActionButton
from wallaby.frontends.qt.widgets.slider.slider import Slider
from wallaby.frontends.qt.widgets.containers.stacked import Stacked
from wallaby.frontends.qt.widgets.edits.plainTextEdit import PlainTextEdit
from wallaby.frontends.qt.widgets.buttons.valueButton import ValueButton
from wallaby.frontends.qt.widgets.buttons.textPopupButton import TextPopupButton
from wallaby.frontends.qt.widgets.labels.imageLabel import ImageLabel
from . import app_rc
