# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fccoelho/Documents/Projects_software/hidx/GUI/main.ui'
#
# Created: Sat Oct  6 11:31:49 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(200, 0))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeWidget = QtGui.QTreeWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.treeWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.treeWidget.setBaseSize(QtCore.QSize(200, 0))
        self.treeWidget.setTabKeyNavigation(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 50))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.dataTab = QtGui.QWidget()
        self.dataTab.setObjectName(_fromUtf8("dataTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dataTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableWidget = QtGui.QTableWidget(self.dataTab)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtGui.QLabel(self.dataTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.rowNumber = QtGui.QSpinBox(self.dataTab)
        self.rowNumber.setMinimum(1)
        self.rowNumber.setMaximum(999999999)
        self.rowNumber.setProperty("value", 99)
        self.rowNumber.setObjectName(_fromUtf8("rowNumber"))
        self.horizontalLayout_3.addWidget(self.rowNumber)
        self.label_2 = QtGui.QLabel(self.dataTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.rowStart = QtGui.QSpinBox(self.dataTab)
        self.rowStart.setMaximum(999999999)
        self.rowStart.setObjectName(_fromUtf8("rowStart"))
        self.horizontalLayout_3.addWidget(self.rowStart)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.dataTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuVisualize = QtGui.QMenu(self.menuBar)
        self.menuVisualize.setObjectName(_fromUtf8("menuVisualize"))
        self.menu_Help = QtGui.QMenu(self.menuBar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setBaseSize(QtCore.QSize(200, 0))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Connect = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/images/text-csv.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Connect.setIcon(icon)
        self.action_Connect.setObjectName(_fromUtf8("action_Connect"))
        self.actionConnect_to_Server = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/images/network-server-database.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect_to_Server.setIcon(icon1)
        self.actionConnect_to_Server.setObjectName(_fromUtf8("actionConnect_to_Server"))
        self.actionE_xit = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/images/application-exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionE_xit.setIcon(icon2)
        self.actionE_xit.setObjectName(_fromUtf8("actionE_xit"))
        self.actionScatterplot_Matrix = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/viz/images/line-plot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScatterplot_Matrix.setIcon(icon3)
        self.actionScatterplot_Matrix.setObjectName(_fromUtf8("actionScatterplot_Matrix"))
        self.actionMotion_Chart = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/viz/images/bubble.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMotion_Chart.setIcon(icon4)
        self.actionMotion_Chart.setObjectName(_fromUtf8("actionMotion_Chart"))
        self.actionAbout_HiDX = QtGui.QAction(MainWindow)
        self.actionAbout_HiDX.setObjectName(_fromUtf8("actionAbout_HiDX"))
        self.actionAbout_PyQT = QtGui.QAction(MainWindow)
        self.actionAbout_PyQT.setObjectName(_fromUtf8("actionAbout_PyQT"))
        self.actionReload = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/images/reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReload.setIcon(icon5)
        self.actionReload.setObjectName(_fromUtf8("actionReload"))
        self.action_Help = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/viz/images/system-help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Help.setIcon(icon6)
        self.action_Help.setObjectName(_fromUtf8("action_Help"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.menu_File.addAction(self.action_Connect)
        self.menu_File.addAction(self.actionConnect_to_Server)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionE_xit)
        self.menuVisualize.addAction(self.actionScatterplot_Matrix)
        self.menuVisualize.addAction(self.actionMotion_Chart)
        self.menu_Help.addAction(self.actionHelp)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.actionAbout_HiDX)
        self.menu_Help.addAction(self.actionAbout_PyQT)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuVisualize.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.action_Connect)
        self.toolBar.addAction(self.actionConnect_to_Server)
        self.toolBar.addAction(self.actionReload)
        self.toolBar.addAction(self.actionE_xit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMotion_Chart)
        self.toolBar.addAction(self.actionScatterplot_Matrix)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Help)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "HiD Data Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Showing:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "records starting at", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuVisualize.setTitle(QtGui.QApplication.translate("MainWindow", "Visualize", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Connect.setText(QtGui.QApplication.translate("MainWindow", "&Connect to File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Connect.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect_to_Server.setText(QtGui.QApplication.translate("MainWindow", "Connect to &Server", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect_to_Server.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionE_xit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScatterplot_Matrix.setText(QtGui.QApplication.translate("MainWindow", "&Scatterplot Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMotion_Chart.setText(QtGui.QApplication.translate("MainWindow", "&Motion Chart", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_HiDX.setText(QtGui.QApplication.translate("MainWindow", "About HiDX", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_PyQT.setText(QtGui.QApplication.translate("MainWindow", "About PyQT", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload.setText(QtGui.QApplication.translate("MainWindow", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload.setToolTip(QtGui.QApplication.translate("MainWindow", "Reload data", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Help.setText(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Help.setToolTip(QtGui.QApplication.translate("MainWindow", "Open Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

